### ISSUE TITLE
Authenticate with sessionToken not working

### ISSUE THREAD

**Issue by bilal-codal** [okta/okta-oidc-ios#140]
Current version **okta-sdk-appauth-ios(2.1.0)** not supported Native Sign-In,so we are using **[okta-auth-swift](https://github.com/okta/okta-auth-swift)(Beta)** for native okta login. 
- We are getting SessionToken after successful login via Beta Okta Swift SDK, 
- When we are used that SessionToken for generating OktaTokenManager, we get an error like **Authorization Error: Unexpected response format while retrieving authorization code**

```
extension OktaManager: AuthenticationClientDelegate {
    
    func handleSuccess(sessionToken: String) {
        
        OktaAuth.authenticate(withSessionToken: sessionToken).start().then { (manager) in
               // Success
            }.catch { (error) in
               // Error
        }
    }
```

Can anyone please guide me if can doing anything wrong.

**Comment by IldarAbdullin-okta** [comment]
Hi @bilal-codal ,

Could you please double check that both libraries hit the same endpoint?  Please check `issuer` host in Okta.plist and host that you use in native sign-in flow

Thanks!

**Comment by bilal-codal** [comment]
Hi @IldarAbdullin-okta,

We have verified `issuer` host name in Okta.plist and native sign-in flow from **okta-auth-swift**(Beta) has been same, We still facing the same error.

We have used following code for create `AuthenticationClient` 

> client = AuthenticationClient(oktaDomain: URL(string: "{issuer string from Okta plist}"), delegate: self, mfaHandler: self)

Thank you for helping us

**Comment by IldarAbdullin-okta** [comment]
Hi @bilal-codal ,

Please make sure that you also provided the following parameters in Okta.plist
"scopes" - default values are - "openid profile offline_access"
"clientId" - Id of your native application that has been created in your *.okta.com organization

Please let me know if you have other questions

Ildar

**Comment by bilal-codal** [comment]
Hi @IldarAbdullin-okta ,

We already created an application in *.okta.com organization and used that `clientId` in our Okta.plist

Can you please verify my attechement 
- Code for create `AuthenticationClient` from `okta-auth-swift` SDK
![Screenshot 2019-05-01 at 11 59 15 AM](https://user-images.githubusercontent.com/20395510/57016823-d391e380-6c39-11e9-8e98-642f7f92c940.png)

- `Okta.plist` Screen Short 
![Screenshot 2019-05-01 at 11 56 54 AM](https://user-images.githubusercontent.com/20395510/57017087-1607f000-6c3b-11e9-9034-9ae1c3b53bc3.png)

Thanks!

**Comment by IldarAbdullin-okta** [comment]
Hi @bilal-codal ,

     Your code and configuration are looks good.
     I was trying to find logs for the instance `iamtest` and didn't find any requests with the path `/oauth2/default/v1/authorize`. 
     Could you temporary add me to your **test** org(as admin) so I can test on my side and check the configuration? You can send invite to the following email - ildar.abdullin@okta.com

Ildar

**Comment by IldarAbdullin-okta** [comment]
Hi @bilal-codal ,

Any updates regarding reported issue?

Ildar

**Comment by IldarAbdullin-okta** [comment]
Closing for now. Please re-open if the issue persists
