### ISSUE TITLE
v3.0.0 won't compile in Objective-C project

### ISSUE THREAD

**Issue by prtmshk** [okta/okta-oidc-ios#147]
I installed v3.0.0 and I'm getting an "'OktaOidc/OktaOidc-Swift.h' file not found" compiler error in OIDTokenRequest.m file in CocoaPods. However, importing the same file in my own ViewController.m does not cause this error.
![Screenshot 2019-04-18 at 21 02 40](https://user-images.githubusercontent.com/29314504/56372820-62a40200-621d-11e9-9967-c804c2d2d05c.png)
![Screenshot 2019-04-18 at 20 58 02](https://user-images.githubusercontent.com/29314504/56372821-62a40200-621d-11e9-8e36-8c6340c600d0.png)
I cannot understand what I'm doing wrong that's causing this error. I have tried cleaning my build folder as well as deleting DerivedData.

**Comment by anastasiiaiurok-okta** [comment]
@prtmshk Thanks for submitting this issue. Could you please try to add 'use_frameworks!' into your Podfile and specify whether this helped to resolve your issue?

**Comment by prtmshk** [comment]
Hello and sorry for the late response. I tried adding ```use_frameworks!``` to my Podfile and it resolved the issue with OktaOidc. It did break a few other on Monday which I fixed over the day and now everything's working fine.

Can you give me a one sentence summary of why this worked?

Thank you very much for the solution!

**Comment by IldarAbdullin-okta** [comment]
@prtmshk , OktaOidc pod depends on an Objective-C code so cocoapods can't create static swift lib for you. The only choice is to use dynamic frameworks and therefore option `use_frameworks!`

Closing as issue has been resolved.
