### ISSUE TITLE
iOS: How to log out from Okta iOS SDK v1.0.1?

### ISSUE THREAD

**Issue by KrishnaKishore1992** [okta/okta-oidc-ios#154]
For a native iOS app, i’m using the **OktaAuth cocoa pod(v 1.0.1)**, and I’m trying to get the app to log out so that another user can use the same device.

I use the following: **OktaAuth.clear()**

However, after doing this and presenting the sign-on screen, it automatically logs on again immediately.

Am I missing something that I need to clear or reset or something?

Could you please code snippet how to clear browser cache in iOS app.

Thanks

**Comment by IldarAbdullin-okta** [comment]
Hi @KrishnaKishore1992 ,

`OktaAuth.clear()`  just removes access token from the keychain. It doesn't delete session token
In version `2.0.0` we implemented `signOutOfOkta` function that you can use for sign out flow

Ildar
