### ISSUE TITLE
How to open up the URL of the site protected by SSO?

### ISSUE THREAD

**Issue by volkanbicer** [okta/okta-oidc-ios#165]
I've already logged in and I'm just trying to open up the URL of the site protected by SSO, how it could be done?

**Comment by nodediggity** [comment]
I'm have a similar requirement, my current approach is to cache my authentication cookies and ensure they are set on the browser attempting to render the sso link.

Not sure about this approach though and would love to know if something native exists within OKTA?

**Comment by IldarAbdullin-okta** [comment]
OKTA disables persistent cookies by default therefore SSO doesn't work. To enable it you have to use REST API and change some parameters. Unfortunately you can't change that setting via org web site
The resource that you have to change is SignOn Policy Rule, details are [here](https://developer.okta.com/docs/reference/api/policy/#okta-sign-on-policy)
Parameter that you have to change is `usePersistentCookie`, which has `false` value by default
I recommend to use [postman collection](https://developer.okta.com/docs/reference/postman-collections/) to simplify work with REST API

I'm also planning to create guide how to enable SSO with concrete examples what end-points to hit and what request parameters to use. It will be posted on developer's portal

**Comment by nodediggity** [comment]
It turns out the issue I had was actually related to setting up my `OktaOidcStateManager` incorrectly.

**Wrong**
`manager = OktaOidcStateManager.readFromSecureStorage()`

**Working**
`manager = OktaOidcStateManager.readFromSecureStorage(for: oktaOidc.configuration)`

Thanks for coming back to me none the less :)

**Comment by IldarAbdullin-okta** [comment]
Guide is now available: https://developer.okta.com/docs/guides/shared-sso-android-ios/ios/overview/
