### ISSUE TITLE
OktaOidcMetadataDiscovery.run() doesn't surface errors generated by OIDServiceDiscovery initializer

### ISSUE THREAD

**Issue by jrtibbetts** [okta/okta-oidc-ios#168]
When `OktaOidcMetadataDiscovery.run()` creates an `OIDServiceDiscovery` object from the `oktaAPI.get()` call, it doesn't pass in an error pointer to get the specific error, so it just calls `callback()` with a generic `parseFailure`, which isn't very helpful. When I stepped into the `OIDServiceDiscovery` initializer in the debugger, I found that my problem was simply a missing `issuer` field in the plist, but it would have taken me far less time to find that if the error had been propagated up.

(This was originally posted to the [sample project](https://github.com/okta/samples-ios/issues/57); @IldarAbdullin-okta suggested that I post it here instead.)

**Comment by IldarAbdullin-okta** [comment]
Fixed
