### ISSUE TITLE
"Failed to parse and/or convert object."

### ISSUE THREAD

**Issue by lukenewman** [okta/okta-oidc-ios#175]
i'm testing out my client's production okta setup, but am getting the above error when attempting to present a sign in prompt (also see screenshot).

here's the config dictionary that the `OktaOidcConfig` is being constructed from:

`["redirectUri": "com.io.client:/callback", "issuer": "https://client.okta.com/oauth2/default", "logoutRedirectUri": "com.io.client:/logout", "clientId": "20characterID", "scopes": "openid profile offline_access"]`

<img width="584" alt="Screen Shot 2019-07-29 at 11 58 14 AM" src="https://user-images.githubusercontent.com/5315645/62072010-b904e180-b20b-11e9-9c58-601d4cd32781.png">

what's weird is that i don't get the error when the config dictionary is the following:

`["redirectUri": "com.io.client:/callback", "issuer": "https://client.oktapreview.com/oauth2/default", "logoutRedirectUri": "com.io.client:/logout", "clientId": "different20characterID", "scopes": "openid profile offline_access"]`

happy to reach out to okta support, but figured i'd start with the sdk first. not sure how to find out what is tripping up the parse.

thanks!

**Comment by IldarAbdullin-okta** [comment]
Hi @lukenewman ,

As a first auth step SDK hits the `https://client.okta.com/oauth2/default/.well-known/openid-configuration` endpoint and gets the following response:
`{"errorCode":"E0000015","errorSummary":"You do not have permission to access the feature you are requesting","errorLink":"E0000015","errorId":"oaeJIw7yus2SWWQexbEJQ43fA","errorCauses":[]}`
That is the reason why you see `Failed to parse` error from SDK. Looks like your org doesn't have an auth server called `default`, so you have to create your own server. I would recommend to contact Okta customer support so they will help to resolve this

You also can try to use Okta auth server. Just update your `issuer` parameter:
`"issuer": "https://client.okta.com"`

**Comment by lukenewman** [comment]
@IldarAbdullin-okta thanks for the info. changing the issuer parameter resulted in the same error, however. we will contact okta support. thanks!
