### ISSUE TITLE
File not found OIDAuthorizationService.h

### ISSUE THREAD

**Issue by wmtylerdavis** [okta/okta-oidc-ios#188]
When updating my app to latest GoogleSignIn SDK, which brings in a dependency to AppAuth, I ran into several preprocessor issues for File Not Found. 

Changing several imports locally from #import "OIDAuthorizationService.h" to #import <OktaOidc/OIDAuthorizationService.h> worked to correct the issue.

But the okta-oidc framework should be bringing in AppAuth as a dependency (like GoogleSignIn), not copying the files.

**Comment by IldarAbdullin-okta** [comment]
We did this intentionally as we have some Okta specific modifications and fixes in AppAuth files.
However AppAuth has finally released stable GA version 1.x.x, so we probably reconsider our approach

**Comment by wmtylerdavis** [comment]
Yeah, I understand the intention. At a minimum, removing the naming collisions `#import <OktaOidc/...h>` can prevent a lot of headaches.
