### ISSUE TITLE
OKFA MFA

### ISSUE THREAD

**Issue by manigandanramaratnam** [okta/okta-oidc-ios#194]
When the MFA is enabled in the application level (through MFA signOn policy), the authenticate method is breaking. May you please advise how to go about this?

This is the error response as the result of calling the authenticate method.
APIError : "Authorization Error: Unexpected response format while retrieving authorization code."

**Comment by IldarAbdullin-okta** [comment]
Hi @manigandanramaratnam ,

Could you provide more info? How you getting session token?

Ildar

**Comment by manigandanramaratnam** [comment]
**Here’s how I get the session token:**

OktaAuthSdk.authenticate(with:{okta domain}, username: {user name}, password: {password}, onStatusChange: { (status) in
 }) {(error) in
 }

**Access token is obtained like below and the failure happens here:**

oidcClient.authenticate(withSessionToken: sessionToken, callback: {stateManager, error in
})

Based on my debugging so far, i see the "v1/authorize" call made by the SDK is returning the whole factor enrollment options as HTML response. 

In OIDAuthorizationService, 
session.dataTask(with: urlRequest) {(data, response, error) in
            guard let response = response as? HTTPURLResponse else {
                callback(nil, error)
                return
            }

The MFA is set in the application level like below:
<img width="752" alt="Screen Shot 2019-10-16 at 5 35 52 PM" src="https://user-images.githubusercontent.com/56657877/66964172-7947dc00-f03b-11e9-9f06-3529fca87516.png">

**Comment by manigandanramaratnam** [comment]
Hi @IldarAbdullin-okta, please let me know if i've provided sufficient details or if you require any further information.

**Comment by IldarAbdullin-okta** [comment]
This type of issue could not be caused by MFA. Make sure that your settings are correct and your issuer url is the same in both auth-swift and oidc-ios SDKs

**Comment by manigandanramaratnam** [comment]
Hi @IldarAbdullin-okta,

The url string used for getting the session token is: "https://{masked}.okta.com"
The issuer used for getting the access token is: "https://{masked}.okta.com/oauth2/default"

I've uploaded my test code here for your reference: https://github.com/manigandanramaratnam/Okta-Custom

If the sign on policy for MFA is set against Security > Authentication in Okta portal then everything works properly.
However if the sign on policy for MFA is set under Application > Sign on tab (and not under security > authentication), then it fails while getting access token.
Is this way of setting the sign on policy correct?

**Comment by IldarAbdullin-okta** [comment]
Hi @manigandanramaratnam ,

This is strange that MFA settings on application level can affect tokens exchange flow. I will check this with my environment and will let you know

Thanks,
Ildar

**Comment by IldarAbdullin-okta** [comment]
So, exchange flow is being failed here because Okta server can't check whether user was challenged with MFA or not. Native sign-in flow doesn't use `client_id`, so backend can't evaluate your application level sign-on policy. So what is available for the backend is your org sign-on policy. This is the limitation for native sign-in flow
Application level sign-on policies can only be used for the sign-in flow via sign-in widget(SIW)

**Comment by freak4pc** [comment]
This still seems to be an issue? 🤔

**Comment by johnkxiong** [comment]
This still seems to be an issue!!!
