### ISSUE TITLE
SecureStorage key issues (-25300 errSecItemNotFound)

### ISSUE THREAD

**Issue by gabehoffman** [okta/okta-oidc-ios#200]
I've been updating our apps to the new SDK on version 3.x, and I'm trying to use the new secure storage methods. API looks great, seems to be fine to implement, but in practice it doesn't work. Error to retrieve the data every time, and I'm using the sample code. 

Then I look into the code for
`.readFromSecureStorage` and `.writeToSecureStorage` and they are reading and writing to fundamentally different keys. Restore is using it's own key - `"OktaAuthStateManager"` but the write is using `"self.clientId"` as the key. So I'm guessing that's a problem. And then the example code uses a 3rd key - `let authStateData = try self.secureStorage.getData(key: "okta_user")`. Seems like something isn't correct here. Not sure how this would ever work. And when I changed the code to use `OktaAuthStateManager` for both storage and retrieval, it worked like I think it should.

Is this a bug or am I missing something about the intended usage?

**Comment by IldarAbdullin-okta** [comment]
Hi @gabehoffman ,

Please use the following function for reading data:
`class func readFromSecureStorage(for config: OktaOidcConfig) -> OktaOidcStateManager?`

Function `class func readFromSecureStorage() -> OktaOidcStateManager?` will be deprecated soon as we left it for migration purposes.

Sorry for confusion, I think we should make it more clear in README file

Ildar

**Comment by gabehoffman** [comment]
Ok, I made those changes, thanks for confirming that change. It did solve the problem. However, when I pull the `stateManager` out of storage. The only token it has is the `refreshToken`, no `idToken` and no `accessToken` they are both nil. Is that on purpose, or is something else going wrong?

And if it's on purpose, then what's this example showing? 
https://github.com/okta/samples-ios/blob/bf608702818256517dca8d0188b577362038c087/browser-sign-in/OktaBrowserSignIn/WelcomeViewController.swift#L44

**Comment by IldarAbdullin-okta** [comment]
Both `accessToken` and `idToken` can be `nil` when they are expired. Could you check this?

**Comment by gabehoffman** [comment]
Our dev environment has very short lived tokens to make our lives easier with debugging, but it is as you said, if I try it right away they are there, if it's beyond their expiration, then the data is gone. Thanks for the clarification. I'll go ahead and close this.

**Comment by gabehoffman** [comment]
I can retrieve the payload of the accessToken now, but it doesn't have all the data that it should when I use `try OktaOidcStateManager.decodeJWT(accessToken)`.
For instance the payload that function returns is missing `active` and `username`, refreshToken is missing `active` as well.
Which is a real problem because I am using the `Codable` convinces to turn those JSON structures into concrete data types. They are going in with a certain structure but coming out with another it seems.

**Comment by IldarAbdullin-okta** [comment]
`Access token` is just base64 encoded string that is saved as-is without any modifications. Can you double check content of JWT before saving and after restoring?

**Comment by gabehoffman** [comment]
Ok, I can confirm it's the same thing going in and coming out. The part that's confusing then is that the payload that comes as part of introspection of the access token has some additional data in it that is not a part of access token data model. So the introspection payload is in fact the access token plus some info. This is an important distinction when using the `Codable` protocol, which makes life really easy for you, if you know what to expect.

I was hoping to avoid excessive introspection calls, and extra async logic. But it looks like you have to do introspection to get that data.

**Comment by gabehoffman** [comment]
That `accessToken` plus some data. Is that just `active` and `username` or what else am I missing.

**Comment by gabehoffman** [comment]
I kept digging in and this is what the `OktaOidcStateManager.decodeJWT(accessToken)` gives me vs what the `stateManager.introspect(token: accessToken)` (with the same data being removed)

`JWT DECODE`
```
{
    "aud": "Internal Clients",
     ...
    "cid": "[removed]",
    ....
    "scp": [ "offline_access", "openid", "profile" ],
   ...
    "ver": 1
}
```

`INTROSPECTION`
```{
    "active": true,
    "aud": "Internal Clients",
    ...
    "client_id": "[removed]",
    ...
    "scope": "offline_access profile openid",
    ...
    "token_type": "Bearer",
    "username": "user@cfaxyz.com"
}
```
Major Differences - 
`active` (not in both, that's fine, I get that)
but why does `cid` become `client_id`, `scp` become `scope` (and not an array)
`token_type` and `username` are only available in the introspection (maybe that makes sense, but why not have username in both?)
`ver` is only available in JWTdecode (not sure what that's about)

**Comment by IldarAbdullin-okta** [comment]
`Introspect` doesn't return you the same JWT structure of the token, it is just a description of the token and API response is OKTA specific. Please refer to the documentation: https://developer.okta.com/docs/reference/api/oidc/#introspect
