### ISSUE TITLE
iOS 13 ASWebAuthenticationSession sign-in alert dismissed immediately

### ISSUE THREAD

**Issue by volkanbicer** [okta/okta-oidc-ios#201]
I tested it with SDK 3.5.2, when I call *signInWithBrowser* function it always fails

**Comment by IldarAbdullin-okta** [comment]
Hi @volkanbicer ,

Could you provide more details? Did you test on simulator or device? What exact iOS version? What is your XCode version? What error message you see? Did you try to test on iOS 12?

Ildar

**Comment by volkanbicer** [comment]
I tested both on simulator and device.

- XCode version 11.2.1
- iOS version 13.2.1

I tested with older iOS versions and it's working. When I call signInWithBrowser function, I see UIAlerViewController that says "*** wants to use ** to sign in " and it dismissed in 1 second.

**Comment by IldarAbdullin-okta** [comment]
Please keep tracking this issue as well - https://github.com/openid/AppAuth-iOS/issues/447
I think this is the same issue that you see. I can't reproduce it on both simulator and device

**Comment by volkanbicer** [comment]
@IldarAbdullin-okta thank you very much. I saw the issue. I was passing a new UIViewController instance as from parameter when I call signInWithBrowser function. But as I see it's not a strong reference anymore. Now I'm closing this issue.l
