### ISSUE TITLE
Xcode 11.2.1 - Okta OIDC Version 3.3.0 - Issue in SignWithBrowser

### ISSUE THREAD

**Issue by RajasekaranNeethipathi** [okta/okta-oidc-ios#202]
<img width="1154" alt="Xcode 11 2 1 - SignWithBrowser - Okta oidc 3 3 0" src="https://user-images.githubusercontent.com/17060326/70592604-69461600-1c00-11ea-91e5-fbf382d51963.png">

Hi Team, We are experiencing issue in the SignWithBrowser method while deploying our app  integrated with Okta Oidc 3.3.0 using Xcode 11.2.1 in both simulator and device with iOS 13.2 

Please find attached the screenshot mentioning the error (Authorisation error. Operation couldn't be completed.  org.openid.appauth.general error -3) in SignWithBrowser method. 

Our app is displaying the login pop up "App wants to user xxx.com" to Sign in" correctly while deployed via Xcode 10.2. 

We are seeing the same error (using Xcode 11.2.1) in SignWithBrowser in the Example apps downloaded from https://github.com/okta/okta-oidc-ios/releases/tag/3.3.0 as well. 
<img width="559" alt="Example app - Xcode 11 2 1" src="https://user-images.githubusercontent.com/17060326/70593076-c1c9e300-1c01-11ea-8c7a-817226e4d92d.png">

Please guide us on resolving this issue while deploying the app using Xcode 11.2.1

**Comment by IldarAbdullin-okta** [comment]
Hi @RajasekaranNeethipathi,

OIDC SDK 3.3.0 doesn't support iOS 13.0. Please start using latest SDK 3.5.2

Ildar
