### ISSUE TITLE
Compatibility of OktaOidc with Swift 5.1 and 5.2

### ISSUE THREAD

**Issue by codepadma** [okta/okta-oidc-ios#203]
Can we make sure OktaOidc is compatible with Swift5.1 and 5.2 ?

**Comment by anastasiiaiurok-okta** [comment]
@codepadma The Okta OIDC lib uses Swift 4.2 which is source compatible with Swift5.X by default.
Please, add more details if you are facing any issues with Swift 5.X compatibility.
