### ISSUE TITLE
[Question ] OktaOidcStateManager for App Groups

### ISSUE THREAD

**Issue by miguel-jimenez-0529** [okta/okta-oidc-ios#206]
Hi guys, I would like to know if there is a way to access a previously stored `OktaOidcStateManager` from an extension?
I imagine it should be thorough **App Groups**, but I can't find where to add my `group identifier`  into the SDK to achieve this.

Thanks in advance for your time.

**Comment by IldarAbdullin-okta** [comment]
Hi @miguel-jimenez-0529 ,

You have to use your own storage mechanism for storing sharable data. I would recommend to use Okta's [secure storage library](https://github.com/okta/okta-storage-swift), which is very lightweight Swift wrapper for the keychain API. It allows you to use `app groups`, `biometric` and other features

Ildar
