### ISSUE TITLE
UI Test Failure

### ISSUE THREAD

**Issue by saulurias** [okta/okta-oidc-ios#208]
Not being able to find the textfields from the webview, took the code from your examples and it used to work but now did stop working.

<img width="1028" alt="Screen Shot 2020-02-09 at 12 05 59" src="https://user-images.githubusercontent.com/11281932/74107365-abbe9d00-4b34-11ea-87fd-0644fa2e7a51.png">

**Comment by IldarAbdullin-okta** [comment]
It is most likely due to changes in the implementation of Okta's Sign In Widget. However you can reference to the UI tests in this repo which are always up to date: https://github.com/okta/okta-oidc-ios/blob/master/UITests/Okta_UITests.swift

Ildar
