### ISSUE TITLE
This library is worst library

### ISSUE THREAD

**Issue by govindprasadgupta** [okta/okta-oidc-ios#210]
This library is the worst library I have seen.

1. Did you ever test the signOutFromOkta method? After tapping logout, application shows an alert to confirm. This alert message is the same as sign in-browser alert.

**Sign -in alert:**
<img width="571" alt="Sign_in alert" src="https://user-images.githubusercontent.com/2104937/75511777-406e3980-5a15-11ea-963b-25980550f2de.png">

**Signout alert**
<img width="571" alt="sign_out alert" src="https://user-images.githubusercontent.com/2104937/75511789-46641a80-5a15-11ea-978d-951a6b5f3c09.png">
see both the alerts are the same.

If you do not know this defect then your employee is making you fool. 
If you know but you are releasing product then you are making your employee 'Chutiya' (fool).
 
2. SAML sign in from okta page is not working properly.
3. Sign out for SAML logged in user is also not working.

Kindly test your product then release it.

**Comment by IldarAbdullin-okta** [comment]
Hi @govindprasadgupta ,

System pop-up for sign-out flow is known iOS issue. Please refer to AppAuth-iOS issue - https://github.com/openid/AppAuth-iOS/issues/461.
Regarding SAML please create separate issues and explain what is the problem

Ildar

**Comment by govindprasadgupta** [comment]
You know this issue and you released a package with the bug.
You did not mention this bug in the readme file or in any tutorial.
At lease mention this issue in the Github readme and OKTA tutorial page.

**Comment by IldarAbdullin-okta** [comment]
Would like to omit long discussions why Google AppAuth-iOS and Okta decided to create release with minor iOS bug

Regarding `Known-Issues` section in README file - it is definitely a good idea! We will add it. Thanks
