### ISSUE TITLE
No error or success response after login

### ISSUE THREAD

**Issue by DrishyaOB** [okta/okta-oidc-ios#211]
Hi,

I am using this SDK for integrating SSO in my ios application. I configured my application in the Okta developer account and wrote all the functions as specified in the document.

**App Flow:**
I log in with the sample application as provided in the below link:
[SDK Sample App](https://github.com/okta/okta-oidc-ios)

After tapping on the Sign-in button, the application was redirected to the Okta login page. I entered the credentials and after that, the login page just dismissed without giving any response in the code.

Code Used:

`        oktaOidc?.signInWithBrowser(from: self, callback: { [weak self] stateManager, error in
`
Neither I got the error or the stateManager value.

After sign in, not receiving any tokens

A prompt reply is highly appreciated.

**Comment by DrishyaOB** [comment]
The issue has been resolved.

There was upper case in the bundle identifier which caused the issue. Made redirect uri's all lower case. The following link helped:

[Code Not Exchanged For Tokens in iOS Auth Code Flow
](https://support.okta.com/help/s/article/Code-Not-Exchanged-For-Tokens-in-iOS-Auth-Code-Flow)

Thanks

**Comment by IldarAbdullin-okta** [comment]
Thank you, @DrishyaOB. I'm happy that you resolved the issue!
