### ISSUE TITLE
Moving `openURL` Related Functions to a Different Subspec

### ISSUE THREAD

**Issue by superarts** [okta/okta-oidc-ios#213]
I assume `OktaOidc` is designed as a "generic" library to be used by any iOS targets, but current, the `openURL` related functions prevent it to be included in targets like a Today Extension.

## How to reproduce

Create a Today Extension, add `OktaOidc` to it, and the project cannot be built.

## Suggestions

There are multiple files in this repo calls `openURL` API, e.g. [this one](https://github.com/okta/okta-oidc-ios/blob/6d88e41413c4c0ba4424a7f625a0c418980f812e/Okta/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m). It would be good if these modules can be separated as a different subspec, for example something like `OktaOidc/Redirect`.

Specifically, one possible design pattern is to extract `openURL` related functions out, create a protocol, provide the implementation inside a subspec, and leave a place to inject the dependency. In this case, a "host" app can either pull in this subspec, or provide it's own implementation and inject it into Okta SDK.

**Comment by IldarAbdullin-okta** [comment]
Hi @superarts ,

I like your suggestion regarding splitting sources into sub-specs. However this looks as a cocoapods specific approach
On the other hand we relatively soon going to deprecate iOS versions below 11 and therefore we will remove all `openURL` related functionality

Ildar

**Comment by superarts** [comment]
Nice! That would be great! Any ETA for the new version, or any issues that we can link with our issue tracker please?

**Comment by IldarAbdullin-okta** [comment]
@superarts ,
We can drop iOS11 support in June. Can you check whether any other additional work is required to help with your request?
You are also welcome to contribute, I can merge your changes and create release

**Comment by superarts** [comment]
> @superarts ,
> We can drop iOS11 support in June. Can you check whether any other additional work is required to help with your request?
> You are also welcome to contribute, I can merge your changes and create release

Sounds good! Since we already deployed a workaround by not making auth related calls in Today extension, we don't have any urgent needs anymore. But I'll forward your message to our framework team. Thank you!

**Comment by oleggnidets-okta** [comment]
We've released a new version with fixed app extension support [3.10.6](https://github.com/okta/okta-oidc-ios/releases/tag/3.10.6). 

The issue should be fixed. Otherwise, feel free to reopen it.

Thank you for using Okta!
