### ISSUE TITLE
Oauth and SSO in WKWebview

### ISSUE THREAD

**Issue by afmsxpand** [okta/okta-oidc-ios#214]
Hi,

I'm using the `signInWithBrowser` option to signin the user, but then i can't find a way to "inject" this session into a WKWebview that needs to show a Tableau dashboard (configured with SAML).

**What i did**
- I've changed the `usePersistentCookie` as stated in https://github.com/okta/okta-auth-swift/issues/98 but Tableau is still asking for login.

- Tried to get the cookies from `HTTPCookieStorage.shared.cookies` after login and inject them into my WKWebview before loading the Tableau URL....still same problem.

- Send the Bearer token in Authorization Header of the request that is loaded in webview

from the [documentation](https://developer.okta.com/docs/guides/session-cookie/overview/) i think i can add a session cookie to the webview but all of the methods require a session token that i don't know how to retrieve using this SDK...

**Comment by IldarAbdullin-okta** [comment]
Hi @afmsxpand ,

I think you definitely need to enable persistent cookies on Okta side. Then as a next step I would try to authenticate via [AuthN SDK](https://github.com/okta/okta-auth-swift), get session token and exchange it to access token view OIDC `authenticate` method. Then load a web view and check whether SSO works or not

Ildar
