### ISSUE TITLE
Missing @objc for OktaOidcStateManager writeToSecureStorage and readFromSecureStorage methods

### ISSUE THREAD

**Issue by benv33** [okta/okta-oidc-ios#218]
Hi,
I was following the doc to integrate the sdk  and tried to replicate the different steps in my Objective-C  project. I noticed that some methods are missing the @objc attribute for OktaOidcStateManager class to manage caching of session tokens:
writeToSecureStorage 
readFromSecureStorage

Would you be able to add them?

Thanks

**Comment by IldarAbdullin-okta** [comment]
Hi @benv33 ,

Thanks for pointing this out. Let us add `@objc` attribute for the storage functions. Thanks!

Ildar

**Comment by benv33** [comment]
Hi Ildar,

I tried version 3.6.0 that was released today and I have this errors when compiling:

_/Users/mTripDev2/Documents/mTripProject/Code/mTrip/mTripDev/Pods/OktaOidc/Okta/OktaOidc/iOS/OktaOidc+Browser.swift:71:23: Cannot override 'resume' which has been marked unavailable: Unused on iOS 11+_

_/Users/mTripDev2/Documents/mTripProject/Code/mTrip/mTripDev/Pods/OktaOidc/Okta/OktaOidc/Internal/iOS/OktaOidcBrowserProtocolIOS.swift:31:6: Protocol members can only be marked unavailable in an @objc protocol_

Thanks,
Ben

**Comment by IldarAbdullin-okta** [comment]
Hi Ben,

Thanks for letting me know! Trying on different projects, don't see the issue. What iOS version your projects supports?
Probably I need to check with lower iOS versions

Ildar

**Comment by benv33** [comment]
I use latest Xcode and my deployment target is iOS 11.4

Ben

**Comment by IldarAbdullin-okta** [comment]
Let me double check in pure obj-c project. Probably this could be the case!

**Comment by IldarAbdullin-okta** [comment]
Reproduced compilation errors in obj-c project.

@benv33 , could you modify your podfile to work with the branch `origin/objc_fix` and let me know how it works for you. Branch also addresses your original issue

Ildar

**Comment by benv33** [comment]
@IldarAbdullin-okta, it's working, thanks!

**Comment by IldarAbdullin-okta** [comment]
Thanks for checking! I will create new pod release shortly!

**Comment by IldarAbdullin-okta** [comment]
OIDC 3.6.1 version has been released
