### ISSUE TITLE
Failed to compile the project: 'OIDAuthState.h' file not found

### ISSUE THREAD

**Issue by gao-sun** [okta/okta-oidc-ios#220]
okta-oidc-ios version: 3.6.1
Xcode version: 11.4

Use Carthage for package management

1. `carthage update` executed successfully
2. added framework files in both `input.xcfilelist`/`output.xcfilelist` 
3. try to compile the project in Xcode, shows `'OIDAuthState.h' file not found` and `Failed to import bridging header 'project/Carthage/Checkouts/okta-oidc-ios/Okta/OktaOidc/OktaOidc.h'`

change version to `3.5.2` works

**Comment by cnfuzedRk62** [comment]
Hi @gao-sun  I am facing same issue with Xcode 11 with running ios 13 Swift 5. But in my case I am getting 'OIDAuthorizationService.h' file not found . I don't know how this can be resolved. Can anyone Know what is wrong with this.

**Comment by IldarAbdullin-okta** [comment]
Hi @gao-sun ,

Thanks for reporting this. Looks like OktaOidc umbrella file is not included into the framework after carthage build. However that works fine in the repo workspace. Let me take a look

Ildar

**Comment by IldarAbdullin-okta** [comment]
@gao-sun , please clean carthage cache and try to build 3.6.1 again. It should work now. Thanks!

**Comment by gao-sun** [comment]
Thank you for such quick response @IldarAbdullin-okta ! Your fix works. 

@cnfuzedRk62 You may try to follow the same steps as Ildar suggested
