### ISSUE TITLE
Build failed when compiled it shows 'OIDAuthorizationService.h' file not found

### ISSUE THREAD

**Issue by cnfuzedRk62** [okta/okta-oidc-ios#221]
Hey team i am integrating sign in with okta in my ios App. I am using cocoa pods here is my full detail of all versions:-

Xcode 11.4
Swift 5
ios 13
. When I tried to compile the project it throws the error with **'OIDAuthorizationService.h' file not found**

error type:-

Lexical or Preprocessor Issue Group. in Okta framework. Please help me out from this 
Thank you.

**Comment by cnfuzedRk62** [comment]
Hi @IldarAbdullin-okta  Thanks for the reply . Okay I will share my pod file with you. Actually i noticed the issue in my app I am using Sign in with google Sdk as well. And it is using AppAuth framework too, means when I install pods of Signin with google framework it automatically downloaded its dependency framework ie:- AppAuth framework. I think that my cause the error. Because when I removed the pod of Googlesignin then it works fine. So do you have any idea why this happened in case of Okta framework?


Here is my pod file:-


platform :ios, '11.0'
```
use_frameworks!

def shared_pods
pod 'SDWebImage', '~> 4.0'
pod 'IQKeyboardManagerSwift'
pod 'SwiftyJSON', '~> 4.1'
pod 'RealmSwift'
pod 'Intercom', '~> 5.4.1'
pod 'PusherSwift'
pod 'youtube-ios-player-helper', '~> 0.1'
pod 'HCSStarRatingView', '~> 1.5'
pod 'FSCalendar', '~> 2.8'
pod 'OpenTok'
pod 'WKWebViewJavascriptBridge', '~> 1.2.0'
pod 'OpalImagePicker'
pod 'URLEmbeddedView'
pod 'Fabric', '~> 1.10.0'
pod 'Crashlytics', '~> 3.13.0'
pod 'Firebase/Core'
pod 'NVActivityIndicatorView'
pod 'UnsplashPhotoPicker', '~> 1.0'
pod 'Alamofire'
pod 'GrowingTextView', '0.6.1'
pod 'DTCoreText',  '~> 1.6'
pod 'SexyTooltip', '~> 1.2'
pod 'ESTimePicker','~> 0.4'
pod 'PDFReader'
pod 'Hakawai'
pod 'Kanna', '~> 5.0.0'
pod 'ObjectMapper', '~> 3.3'
pod 'MSAL'
pod 'OktaOidc'
pod 'GoogleSignIn'
end
target 'HowNow3.1' do
shared_pods
end

target 'shareExtension' do
   pod 'URLEmbeddedView'
   pod 'Alamofire'
   pod 'ObjectMapper', '~> 3.3'
   pod 'SDWebImage', '~> 4.0'
   inherit! :search_paths
  end



```

**Comment by cnfuzedRk62** [comment]
Hi @IldarAbdullin-okta  The issue has been Resolved.

I have to modify all the #header files from  #import "OIDAuthorizationService.h" to #import <OktaOidc/OIDAuthorizationService.h> worked to correct the issue.

But the okta-oidc framework should be bringing in AppAuth as a dependency (like GoogleSignIn), not copying the files.

This issue stuck my 2 days , it wired.

**Comment by cnfuzedRk62** [comment]
Hi @IldarAbdullin-okta  The issue has been Resolved.

I have to modify all the #header files from  #import "OIDAuthorizationService.h" to #import <OktaOidc/OIDAuthorizationService.h> worked to correct the issue.

But the okta-oidc framework should be bringing in AppAuth as a dependency (like GoogleSignIn), not copying the files.

This issue stuck my 2 days , it wired.

**Comment by keiscool2468** [comment]
@cnfuzedRk62 are you only modify "OIDAuthorizationService.h" instead of all "#import xxx.h"

**Comment by keiscool2468** [comment]
I am also facing this issue

**Comment by keiscool2468** [comment]
> Hi @IldarAbdullin-okta The issue has been Resolved.
> 
> I have to modify all the #header files from #import "OIDAuthorizationService.h" to #import <OktaOidc/OIDAuthorizationService.h> worked to correct the issue.
> 
> But the okta-oidc framework should be bringing in AppAuth as a dependency (like GoogleSignIn), not copying the files.
> 
> This issue stuck my 2 days , it wired.
![image](https://user-images.githubusercontent.com/22214095/95673453-329faa00-0bdb-11eb-9c45-aafc7994e3fd.png)
i got this issue after this
