### ISSUE TITLE
OKTA browser SignIN -Sign Out shows incorrect system dialog

### ISSUE THREAD

**Issue by jasmineelamblakatt** [okta/okta-oidc-ios#224]
I am integrating OKTA browser SignIN in my app. 
For that 
 am using oktaOidc?.signOutOfOkta function to Sign out the user, on calling the function it opens the dialog with the message as "App wants to Use "oktapreview.com" to Sign In "
and on continue it takes to the browser.
This message is misleading as the user wants to Logout but "Sign In" message is shown.
Is there any way to eliminate this dialog?

Or is there any other way to perform logout? I tried clearing access token, Idtoken, and refresh token by calling revoke API, but the session is not cleared coming again to browser it automatically logs in. Thanks in advance.

<img width="246" alt="Screenshot 2020-04-30 at 12 34 22 PM" src="https://user-images.githubusercontent.com/14106534/81143557-bd76db80-8f8f-11ea-9fad-ff6f11951ab7.png">

**Comment by IldarAbdullin-okta** [comment]
Hi @jasmineelamblakatt ,

Calling `signOutOfOkta` API is the only way to kill active OIDC session.
Regarding pop-up, please refer to the following issue - https://github.com/openid/AppAuth-iOS/issues/461
There is currently no way how fix/avoid that system level pop-up

Ildar
