### ISSUE TITLE
Value of type 'OktaOidc?' has no member 'resume'

### ISSUE THREAD

**Issue by djalfirevic** [okta/okta-oidc-ios#231]
Hello,

Any particular reason why I'm getting this?I'm following steps from the `README.md` file.

**Comment by IldarAbdullin-okta** [comment]
HI @djalfirevic ,

README has the following statement - `Redirect is needed if you want to support iOS 10 and older`. In 3.8.0 version we dropped support of iOS9 and iOS10. Do you still need to support them? If yes, you have to use version `3.7.0`

I will also update README and remove section about redirect as it causes confusion. Thanks!

Ildar

**Comment by djalfirevic** [comment]
Thank you for your quick answer!

Now it's clear!
