### ISSUE TITLE
App Extension support

### ISSUE THREAD

**Issue by awazny323** [okta/okta-oidc-ios#235]
Hi,
I have an App Extension where I fetch some data, but to make that API call, sometimes I need to renew AccessToken. Is there any way to use `OktaOidcStateManager` there, because when I add OKTA to App Extension target I get this error.

![Screen Shot 2020-08-19 at 9 40 33 AM](https://user-images.githubusercontent.com/69905302/90642737-c61eb500-e200-11ea-8c19-675f9f077bbe.png)

**Comment by IldarAbdullin-okta** [comment]
Hi @awazny323 ,

This file is part of OIDC core. But I think we don't use this in our Swift implementation. Is it the only issue that blocks you to use SDK in App Ext? I think we can easily delete this file from SDK

Ildar

**Comment by awazny323** [comment]
There is one more place where that error occurs, it's in `OIDExternalUserAgentIOS` class

![Screen Shot 2020-08-20 at 2 06 18 PM](https://user-images.githubusercontent.com/69905302/90808981-d614c280-e2ee-11ea-9747-0e8b7ca7a53b.png)

**Comment by richardpiazza** [comment]
Looks like this is an issue while using the swift package via the Xcode 13 betas. The framework fails to build. Has there been any movement on addressing this?

**Comment by oleggnidets-okta** [comment]
Hey @richardpiazza
We have recorded issue in our tracking system, OKTA-415860. Unfortunate, no progress for now. 
But I believe we'll take the task in progress soon.

**Comment by richardpiazza** [comment]
> Looks like this is an issue while using the swift package via the Xcode 13 betas. The framework fails to build. Has there been any movement on addressing this?

Digging a bit further into this. Looks like Xcode 13 Beta 13 changed some linking behavior (https://twitter.com/twannl/status/1415643870512226307) and packages now need to explicitly mark some api as unavailable for app extensions.

![E6VgHpfXIAEJoIG](https://user-images.githubusercontent.com/1744463/127658524-95f988bb-578c-4040-9d5e-56363a2b8a4a.jpeg)

**Comment by oleggnidets-okta** [comment]
Hey @richardpiazza @awazny323 
We've released a new version [3.10.6](https://github.com/okta/okta-oidc-ios/releases/tag/3.10.6).

Let us know whether it works for you. Feel free to reopen the issue.

Thanks!
