### ISSUE TITLE
README is missing "Sign In with your own UI" section

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-ios#239]
The Android SDK has a [Sign in with your own UI](https://github.com/okta/okta-oidc-android#Sign-in-with-your-own-UI) section. This SDK does not. Please add one so we can link to it from our developer docs. 

FWIW, a [custom sign-in sample](https://github.com/okta/samples-ios/tree/master/custom-sign-in) does exist so we just need the relevant code added.

**Comment by IldarAbdullin-okta** [comment]
@mraible , for custom sign-in you have to use another SDK - https://github.com/okta/okta-auth-swift. We can add few words about custom sign-in and add a reference to AuthN SDK

**Comment by mraible** [comment]
Here's [a link to the docs](https://github.com/okta/okta-developer-docs/pull/1438/files#diff-c4abcde8027340d72a5b78907a9be034R400-R408) I'm trying to update. 

You can see I'm just trying to enhance the Sign-In Widget guide to say it's not embeddable in most native apps, but you can build your own login form with X - and then linking to the relevant docs for that.

What links would you recommend for iOS?

**Comment by IldarAbdullin-okta** [comment]
Please provide the link - https://github.com/okta/okta-auth-swift

I will also update OIDC SDK readme to transfer people to AuthN SDK if they want to build custom UI
