### ISSUE TITLE
Swift Package Manager - Issue with path to source files

### ISSUE THREAD

**Issue by EricDobyns** [okta/okta-oidc-ios#244]
Package.swift does not match the latest swift conventions (Swift 4 & above). Need to update the package.swift file to include the path property pointed at the source files.

https://swift.org/blog/swift-package-manager-manifest-api-redesign/
https://stackoverflow.com/questions/46943952/error-could-not-find-targets-mylib-use-the-path-property-in-the-swift-4-m

<img width="733" alt="Screen Shot 2020-09-18 at 9 36 42 AM" src="https://user-images.githubusercontent.com/7757336/93622725-7879a180-f992-11ea-9c67-9f76d32211c6.png">

**Comment by gao-sun** [comment]
tried to fork and update but got mixed language error, I think there'll be some refactor process.

**Comment by gao-sun** [comment]
@IldarAbdullin-okta do you have any plan on this? we're migrating to SPM and got stuck on Okta libs

**Comment by IldarAbdullin-okta** [comment]
@EricDobyns , @gao-sun , I've reopened https://github.com/okta/okta-oidc-ios/issues/225
There is some additional work required to split Obj-C and Swift code, also need to think how to split platform code - iOS vs OSX

**Comment by sam-w** [comment]
@EricDobyns @gao-sun see https://github.com/okta/okta-oidc-ios/pull/245 for some progress on this. Other contributions very welcome!
