### ISSUE TITLE
OKTA clear method

### ISSUE THREAD

**Issue by chaitanya-neosoft** [okta/okta-oidc-ios#246]
Why delete all keychain items we can delete the specific value for ClientID

**Comment by IldarAbdullin-okta** [comment]
@chaitanya-neosoft , could you provide more details?

**Comment by chaitanya-neosoft** [comment]
A clear() method of OKTA. Clearing complete keychain. Due to this, I am getting the error by generating the Firebase device token. 
Basically My question is why to clear all keychain items? We can only clear the specific key of OKTA from the keychain.

**Comment by IldarAbdullin-okta** [comment]
@chaitanya-neosoft , fully agree. This method clears all keychain items and it can be unexpected behavior by the app layer. I'm going to deprecate this API in next version, so developer should explicitly remove all OIDC records in the keychain. Thanks for reporting this!

**Comment by oleggnidets-okta** [comment]
We've deprecated `clear` method. Please use `removeFromSecureStorage`.
Feel free to reach us out with any questions.

Thanks for contribution!
