### ISSUE TITLE
Documentation for 'login' method is still missing

### ISSUE THREAD

**Issue by OguzErtanAyanlarW** [okta/okta-oidc-ios#251]
On issue #75 and #90, it is suggested that there is an 'undocumented' login method that can be used to pass additional parameters to browser sign-in, an equilevant of Android OIDC SDK's 'AuthenticationPayload.Builder().addParameter("prompt", "login").build()' method.

However, there isnt any documentation for it, how can one use this method to launch Okta webAuth widget on signIn mode and pass parameters ?

**Comment by robertjd** [comment]
HI @OguzErtanAyanlarW , those issues are pretty old and probably leftover from the previous iteration of this library.  @IldarAbdullin-okta can you confirm if it's possible to pass these options through?  Let us know if this is new work to do.

**Comment by IldarAbdullin-okta** [comment]
Hi @OguzErtanAyanlarW ,

In order to use custom claims you can do the following:
```
let config = OktaOidcConfig(with: [“issuer”: “{YourIssuer}”, **“login”: ”prompt”**])
let oidc = OktaOidc(with configuration: config)
oidc.signInWithBrowser(…)
```

In November we want to add convenience method to pass custom claims in `signInWithBrowser` method without creating extra config object.
```
@objc public func signInWithBrowser(from presenter: UIViewController, **customOptions: [String: String] =[: ]**, callback: @escaping ((OktaOidcStateManager?, Error?) -> Void))
```

Ildar

**Comment by OguzErtanAyanlarW** [comment]
Hi @IldarAbdullin-okta, thanks for the response. Sadly, passing the 'prompt':'login' parameter the way you suggested does not work on iOS SDK. (We are on Objective-C btw).

I guess I have to wait for the November release. Thanks for your replies.

**Comment by IldarAbdullin-okta** [comment]
Hi @OguzErtanAyanlarW ,

I've just double checked that option in OIDC SDK and I see` login:prompt` key-pair in `authorize` call:

https://my.okta.org/oauth2/v1/authorize?state=5kQy3Me-nbilBUUWAzyL-uQb-ug7vPLzvTu4CMT5KWg&nonce=841eEacLWIlr0-V4NiTqdRq3V4D9vIhEZhVVjo7PaU8&response_type=code&code_challenge_method=S256&scope=openid&code_challenge=hmXAJm2eJRb89Z0jnNV4t4SRZBCJq6YCNkfmAghXBGg&redirect_uri=com.okta.app://oauth/callback&client_id=okta.63c081db-12345&**login=prompt**

Maybe your IDP doesn't respect this custom OIDC option?

Ildar

**Comment by IldarAbdullin-okta** [comment]
Checked also with Okta IDP. Okta correctly handles `login=prompt` in the query

@OguzErtanAyanlarW , just in case, if you want to disable SSO for the session you have also the following option:
https://github.com/okta/okta-oidc-ios#disable-single-sign-on-for-the-authentication-session

**Comment by OguzErtanAyanlarW** [comment]
We tried both methods again, it sadly didnt worked. Do you know the dates for the November release ? Today we received a release note mail, but this was not included on the release notes.

**Comment by oleggnidets-okta** [comment]
Hi @OguzErtanAyanlarW,
From my understanding, `prompt=login` is equal to `noSSO` [parameter](https://github.com/okta/okta-oidc-ios#disable-single-sign-on-for-the-authentication-session). If the parameter enabled, then the login page is shown despite of stored cache. 

I close the issue for now. If you believe it's not enough, please, re-open. 
Thanks for using Okta!
