### ISSUE TITLE
Improve SignOut UX

### ISSUE THREAD

**Issue by RichiCoder1** [okta/okta-oidc-ios#252]
The unavoidable UX where a user has to consent to Sign Out is pretty confusing. However, with iOS 12 now there is apparently a work-around using the newly minted `ASWebAuthenticationSession` to handle Sign In and calling a normal `SFSafariViewController` to end the session.

Example of another app doing so: https://github.com/blockstack/blockstack-ios/pull/29

**Comment by IldarAbdullin-okta** [comment]
Hi @RichiCoder1 ,

Fully agree, `Sign Out` consent is very confusing. And thanks for the hint with workaround! We will check whether it makes sense to use `SFSafariViewController` to end the session

Ildar

**Comment by jcislinsky** [comment]
Am I understand correctly, that this probably solve the issue with showing the alert: "App Wants to Use oktapreview.com to Sign In" during signOut?

<img width="471" alt="Screenshot_2020-03-26_at_18_37_13" src="https://user-images.githubusercontent.com/7204475/101454898-f619d180-3931-11eb-9b62-673db38e8df8.png">

**Comment by RichiCoder1** [comment]
Hopefully!

**Comment by lander854** [comment]
news on that?

**Comment by jcislinsky** [comment]
Any update here?

**Comment by oleggnidets-okta** [comment]
No updates on this. Making sign out via `SFSafariViewController` is not safe in our library. From abstraction point of view, these classes are not related. 
Imagine if Apple changes this behavior and it stops working. For now it's just a workaround not a solution. 

Consider [workarounds described](https://github.com/okta/okta-oidc-ios#ios-shows-permission-dialogapp-wants-to-use-auth-domain-to-sign-in-for-okta-sign-out-flows) and [this one](https://github.com/okta/okta-oidc-ios/issues/181#issuecomment-797385092).
