### ISSUE TITLE
Unable to log out of app

### ISSUE THREAD

**Issue by philiprenich** [okta/okta-oidc-ios#263]
I'm not sure if I am vastly misunderstanding how this SDK should be used or if there is a bug related to signing out of Okta.

Signing in successfully works like a charm, no worries. But when I use `oktaOidc.signOutOfOkta` (or `oktaOidc.signOut` with various options, including `.allOptions`) I am not locally signed out of the app. On a rebuild, I am required to sign in again which leads me to believe I am successfully signed out of Okta's servers (the server session is destroyed), but within the app `stateManager.authState.isAuthorized` remains true, and the `introspect` method says the token is valid.

I have tried all sorts of styles of `stateManager.clear()` and `.revoke(...)` to no avail.

Lastly, I took the [sample app](https://github.com/okta/samples-ios/tree/master/browser-sign-in) and after some investigation, realised it also is not locally signing out. I tested this by wiring up a simple button to the Sign in screen that just navigates directly to the Authenticated screen. My flow was to sign in -> sign out and be redirected back by the segue -> use my button to get back to the authenticated screen w/out signing back in -> introspect token and see it is valid, but it should not be.

For code samples, there is nothing changed in the sample app that could affect this. In my app, the sign out code looks like this:

```
var options: OktaSignOutOptions = .revokeAccessToken
                options.insert(.signOutFromOkta)
                options.insert(.removeTokensFromStorage)

                oktaOidc?.signOut(with: options, authStateManager: userManager!, from: self, progressHandler: { currentOptions in
                    print(currentOptions)
                }, completionHandler: { success, currentOptions in
                    print(success) // showing True
                    print(currentOptions)
                    print(userManager?.authState.isAuthorized) // showing True (should be False?)
                })
```

I have also tried

```
                oktaOidc?.signOutOfOkta(userManager!, from: self, callback: { error in
                    if let error = error {
                        print(error, error.localizedDescription)
                        let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: .alert)
                        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
                        self.present(alert, animated: true, completion: nil)
                        return
                    }

                    userManager?.clear()
                })
```

What am I doing wrong or is this an issue in the SDK? Thank you for the help!

**Comment by philiprenich** [comment]
I've been able to achieve what I need - immediate UI updates based on the user being authenticated or not - by resetting the `authStateManager` in the completion handler of the first example or after the `.clear()` method in the second. As so:

```
userManger?.clear()
userManager = OktaOidcStateManager.readFromSecureStorage(for: oktaOidc!.configuration)
```

I debugged some of the lower level functions and found the Keychain items indeed being deleted, so re-reading from secure storage will result in a null state manager.

Not sure if this is the intended or best way, but it's working for now. Would be great to get feedback to understand how I should be doing this though.

**Comment by oleggnidets-okta** [comment]
Hi @philiprenich,
Sorry for our late response.

Indeed, `userManager?.authState.isAuthorized` returns `true` after logout. According to documentation: 
> Thw property does not mean that the access is fresh - just that it was valid the last time it was used. Note that network and other transient errors do not invalidate the authorized state.  

Therefore, you shouldn't rely on `isAuthorized` property after logout. Best way is using `introspect` to get know whether the Access Token is valid. 

`OktaOidcStateManager` holds the state of an authorization session. So it's a good way to `clear` and nullify the manager after logout.

**Comment by oleggnidets-okta** [comment]
Closing the issue. If you have any related questions feel free to reopen.
