### ISSUE TITLE
is it using SafarWebViewController or WKWebview for showing Okta login page?

### ISSUE THREAD

**Issue by Abbiee** [okta/okta-oidc-ios#264]
Can someone please tell which methodology it is using? Whether it is using SafarWebViewController or WKWebview?
```
oktaOidc.signInWithBrowser(from: viewController) { stateManager, error in
  if let error = error {
    // Error
    return
  }
```

**Comment by oleggnidets-okta** [comment]
Nice question.

Based on system version:
- iOS 9-10 - `SFSafariViewController` 
- iOS 11 - `SFAuthenticationSession`
- iOS 12-latest version - `ASWebAuthenticationSession`

For technical details investigate [the method](https://github.com/okta/okta-oidc-ios/blob/80afc373adb3468d9eb4821e0c5fa16cafbca8de/Sources/AppAuth/iOS/OKTExternalUserAgentIOS.m#L78).
