### ISSUE TITLE
Custom sign-in only way to auth subsequent requests through Vouch proxy?

### ISSUE THREAD

**Issue by bdruth** [okta/okta-oidc-ios#266]
I think I know the answer to this, but I just want to verify all the things, I guess.

I have a site protected behind [vouch proxy](https://github.com/vouch/vouch-proxy), like [here](https://developer.okta.com/blog/2018/08/28/nginx-auth-request). I have an iOS app based on the [browser-sign-in-and-biometric-storage](https://github.com/okta/samples-ios/tree/master/browser-sign-in-and-biometric-storage) example. As near as I can tell, there's no way for me to login using the browser sign-in flow and then use the tokens (access/id/renew) made available via the state manager to set up a `URLRequest` that would go to the vouch-protected site and redirect through the Okta OIDC flow successfully.

I've done this with a similar app that is based off the custom sign-in example, and with `usePersistentCookie` set, the cookies that are set seem to work for this use-case.

Anything I've missed in my research / debugging / trial &  error?

Thanks!

**Comment by oleggnidets-okta** [comment]
Hey @bdruth ,
Sorry for late response.

I'm not sure we can reproduce your scenario as it requires complex setup. Could you please more specific what is required from iOS SDK? Would `OktaNetworkRequestCustomizationDelegate` help you?

In case your question is mostly related to web widget you may contact [our support team](https://support.okta.com/help/s/?language=en_US).

**Comment by oleggnidets-okta** [comment]
Close as no response. Please, reopen with more details if it's still valid.
Thanks for using Okta!
