### ISSUE TITLE
Unable to save password in SFSafariWebViewController

### ISSUE THREAD

**Issue by trevorholliday** [okta/okta-oidc-ios#271]
Users are not prompted to save their credentials to the KeyChain after a successful login.

**Comment by oleggnidets-okta** [comment]
Thanks for reasonable input. 
We need to investigate the issue in more details. (internal ref OKTA-367743)

Do you have disabled or enabled [noSSO](https://github.com/okta/okta-oidc-ios#disable-single-sign-on-for-the-authentication-session)? Please, provide a line of code (by default it is enabled).

**Comment by trevorholliday** [comment]
noSSO is enabled.  (default not modified).

**Comment by trevorholliday** [comment]
noSSO by default is false.

We have attempted to flip noSSO to true and we still are not presented with the prompt to save the credentials.

**Comment by trevorholliday** [comment]
When we manually set noSSO to false we do see the prompt for saving the password but the SFSafriWebViewController is dismissed too quickly to select the option for saving.

**Comment by oleggnidets-okta** [comment]
Thanks for update. 
From first glance, it looks like an Apple bug. 
Actually, if a device is running on iOS 13 and higher the authentication is done through `ASWebAuthenticationSession`. 

`ASWebAuthenticationSession` does make redirect, therefore the screen is closed and save password prompt is dismissed quickly as you noticed.

Here some proof links:
* https://developer.apple.com/forums/thread/127979
* https://developer.apple.com/forums/thread/657855
* https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/848 - people even reported this to Apple. 

We'll keep track on this and also make an investigation from our side to find possible workarounds.

**Comment by oleggnidets-okta** [comment]
@trevorholliday After additional research I find out that it's **Apple' issue** and we are not able to fix it. One way to fix is showing additional screen as described in [Password Autofill Details](https://authguidance.com/2020/02/22/ios-code-sample-overview/). But that's bad login experience for a user. 

Nonetheless, we've released a new version of web widget, so it contains `autocomplete` set on login form. 
From now, if a user has a saved password (make sure `Settings -> Passwords -> Autofill Passwords`), autofill prompt is being shown. 
Also, after registration prompt to save password is being offered. 

![login](https://user-images.githubusercontent.com/77254185/111966722-e8164800-8aff-11eb-9278-413db0ee17e7.png)
![registration](https://user-images.githubusercontent.com/77254185/111966728-e9477500-8aff-11eb-9860-1a00e6a0cbac.png)
