### ISSUE TITLE
Apple Device Check

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-oidc-ios#272]
Hi all, I was wondering if this SDK supports apple Device Check mentioned here: https://developer.apple.com/documentation/devicecheck.  If not are there any examples or integration patterns?

**Comment by oleggnidets-okta** [comment]
Hi @andrewhamilton-okta ,
Good question as it is a part of security domain. 
This is not something we support in our libraries neither oidc, neither [auth-swift](https://github.com/okta/okta-auth-swift).

[DeviceCheck](https://developer.apple.com/documentation/devicecheck) framework provides two services:
- Secure management of device state 
- Establishing app’s Integrity

I guess you may be more interested in the last one, isn't it?

**Comment by andrewhamilton-okta** [comment]
Wrong person ;). @andrewvanbeek-okta ^^

**Comment by oleggnidets-okta** [comment]
Oops, sorry @andrewhamilton-okta. 

@andrewvanbeek-okta Please, take a look at my question above.

**Comment by oleggnidets-okta** [comment]
@andrewvanbeek-okta App Attest is a way to perform security checks to define that the app is not compromised.

Okta as the Identity Provider asserts that authentication into the system is not compromised. One of the recommended way is using authorization [code flow with PKCE](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/).

So I believe that app' assessing is up to user. Moreover, it requires Apple Developer Account to be involved to generate Apple authentication token and additional work must be done on backend side.

There're few examples (not much for now, as it is brand-new feature starting from iOS 14): 
- [Protecting iOS apps from Jailbreak Tweaks in iOS 14](https://swiftrocks.com/app-attest-apple-protect-ios-jailbreak)
- [Apple' documentation](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity)

**Comment by oleggnidets-okta** [comment]
@andrewvanbeek-okta I close the issue as there's no response. I hope provided information is comprehensive. 
Feel free to reopen it or create a new one.
