### ISSUE TITLE
Okta iOS SDK Data collection

### ISSUE THREAD

**Issue by GlebUstimenkoWMG** [okta/okta-oidc-ios#275]
According to new Apple privacy rules we need to disclosure all data that our app collects and how we use it.

Does Okta iOS SDK collect any data and how they use it?

**Comment by mikenachbaur-okta** [comment]
That's an excellent question @GlebUstimenkoWMG, I'll look into this and will get back to you.

**Comment by mikenachbaur-okta** [comment]
@GlebUstimenkoWMG The SDK itself doesn't collect anything unusual about the user beyond what they supply as part of the authentication process. You might want to refer to the [Okta Privacy page](https://www.okta.com/privacy) to see more specific information.

**Comment by GlebUstimenkoWMG** [comment]
@mikenachbaur-okta Thank you! Now it's clear!
