### ISSUE TITLE
Can a custom authroization endpoint be specified similar to the Android SDK?

### ISSUE THREAD

**Issue by danaronoff** [okta/okta-oidc-ios#276]
The Android SDK allows configuring the client to redirect to a self hosted sign in widget by specifying a custom authorization URL:

```
CustomConfiguration config = new CustomConfiguration.Builder()
    .tokenEndpoint("{yourTokenEndpoint}")
    .authorizationEndpoint("{yourAuthorizeEndpoint}")
    .create();
```

Is there an equivalent mechanism to do that with the iOS SDK? Attempts to define a custom configuration property of `authorizationEndpoint `  do not make a difference.

**Comment by oleggnidets-okta** [comment]
Hi @danaronoff,
Thanks for a good question. iOS SDK doesn't provide a way to set `authorization_endpoint`. 
Configurations are loaded from `{issuer}/.well-known/openid-configuration` url. So the easiest way is changing a configuration file on the server by putting the desired `authorization_endpoint`. 

Will it work for you?

**Comment by danaronoff** [comment]
We are using Okta as our provider (of course), and I am pretty sure we cannot change that configuration on the Okta side - the authorization endpoint is fixed relative to the authorization server url. Is that incorrect?

And, I don't think with the way the SDK behaves we can self host a configuration file ourselves, since the issuer value is derived from the configuration url itself, right?

In other words, right now we have the following as the issuer:
`https://<org name>.oktapreview.com/oauth2/<auth server id>`

If we change the issuer to: `https://<company name>.com/oauth2/<auth server id>` 
and host our own configuration at `https://<company name>.com/oauth2/<auth server id>/.well-known/openid-configuration` 

then the issuer won't match the issuer in the tokens that get minted, even if the configuration is exactly the same save for the authorization endpoint.

**Comment by oleggnidets-okta** [comment]
Yes, you're right. 

> issuer won't match the issuer in the tokens that get minted
If it will be scope of one Authorization Server, then the tokens should be working. Otherwise, according to [docs](https://developer.okta.com/docs/concepts/auth-servers/), you can't mix tokens between different authorization servers. By design, authorization servers don't have trust relationships with each other.

If your business case is about migration to another issuer/domain you may feel free to contact [our support](https://support.okta.com/help/s/?language=en_US) for help.

**Comment by danaronoff** [comment]
The business case is the desire to self host a sign in widget but still use the Okta SDK for IOS. I will close this issue since this is not possible.

**Comment by oleggnidets-okta** [comment]
@danaronoff If you'll have any questions/issues related to SDKs don't hesitate to open an issue. Thanks for reaching out!
