### ISSUE TITLE
Auth code from oidc-sdk

### ISSUE THREAD

**Issue by shreyys** [okta/okta-oidc-ios#291]
Our app uses native flow and uses oidc's authenticate() to fetch tokens directly.
But there is no method to provide authcode without using a browser.
Can you help me out here? 

We need auth code for alexa skill linking from our iOS app

**Comment by oleggnidets-okta** [comment]
Hi @shreyys,
Thanks for using Okta. I am not sure that I understand you correctly. 
If you want to get the authorization code, you can use the `authState` property: `stateManager?.authState.lastAuthorizationResponse.authorizationCode`. Hope it helps. State manager is returned in [callback](https://github.com/okta/samples-ios/blob/eae143a97b571184855bf7eaf07970990d0ab96a/custom-sign-in/OktaNativeLogin/UserProfile/UserProfileViewController.swift#L39).

If it doesn't help, I would be thankful if you provide the detailed case (steps) of the usage.

**Comment by shreyys** [comment]
The auth code returned from `stateManager?.authState.lastAuthorizationResponse.authorizationCode` is already used. The Authcode required by alexa skill linking should be new.
 I'm calling the below Alexa API, and it needs fresh auth code.

```
POST /v1/users/~current/skills/{skillId}/enablement HTTP/1.1
Host: api.amazonalexa.com, api.eu.amazonalexa.com, api.fe.amazonalexa.com
Content-Type: application/json
Authorization: "Bearer {Amazon Access Token}"
{
    "stage": "skill stage",
    "accountLinkRequest": {
      "redirectUri": "https://yourRedirectURI",
      "authCode": "Your user's authorization code from your authorization server",
      "type": "AUTH_CODE"
    }
}
```

Is there any API in the SDK that can generate fresh Auth Code

**Comment by oleggnidets-okta** [comment]
The authorization code itself is obtained from the authorization server. It's not being generated by app.
I'm not sure about a proper way of linking Alexa because it feels like out of the SDK scope. 

Feel free to contact our [support team](support.okta.com/) to help you with set up. Also, consider [the Okta tutorial](https://developer.okta.com/blog/2019/03/20/linking-your-alexa-skils-securely) and [video tutorial](https://www.youtube.com/watch?v=BMEt1xIDVVY).

**Comment by shreyys** [comment]
The 'OKTAuthorizationRequest' resides in the SDK and it's doing exactly what we are looking for but its scope is internal.
[The Auth code generation with PKCE](https://developer.okta.com/docs/guides/implement-auth-code-pkce/use-flow/)
The structure and implementation look like it's used to generate auth code to get session token.

Is there any way we can use it?

**Comment by oleggnidets-okta** [comment]
Authorization code is not the same as PKCE. PKCE Authorization Code Flow builds upon Authorization Code Flow.

PKCE is generated by app but it's assures that an attacker can only intercept the Authorization Code, and they cannot exchange it for a token without the Code Verifier (PKCE).

**Comment by shreyys** [comment]
I understand the Authorization Code flow. 
Here is the issue, we need to have a native auth 2.0 flow in our app and that's why we choose Okta.
But now, we have to link alexa skill from our app and it requires auth code.

We get the auth code using the below URL
`<okta-domain>/oauth2/auseepg9sCHp8o3l81d6/v1/authorize?client_id=<clientID>&response_type=code&scope=openid%20offline_access&redirect_uri=<redirectURL>&state=K7_OmBq9fUu7pOEPYeAgsq7CvHj0AFBSnnKfT1XqJ6Y&login_hint=<username>`

The user has to login into this URL to get the auth code. Its working fine but ITS NOT WHAT WE EXPECT.
The user is already logged into the app. 

I've already opened a case with OKTA, It's been long-awaited.

**Comment by oleggnidets-okta** [comment]
@shreyys Authorization Code is granted to the app by Authorization Server (OKTA). If you say that you need to pass it to Alexa, then, probably, you're doing something wrong, because that's not a way OAuth work. 

The Authorization Server can be Okta. In this case authorization code is returned to the client (Alexa app).

![diagram](https://user-images.githubusercontent.com/77254185/116061097-24067500-a68b-11eb-9911-3c3826743f2d.png)

You must fill in the linking form like on the picture:
![form](https://user-images.githubusercontent.com/77254185/116061358-6d56c480-a68b-11eb-8fb9-6e6b5164f3cf.png)


I am not aware about Alexa Skill service configuration. You should investigate their and our documentation about that. At least, taking Auth code on mobile side and sending it to Alexa Service definitely indicates that something is not correct. 

* [Setup Alexa Account Linking](https://alexaworkshop.com/en/smart-home/6.account-linking.html)
* [Account Linking Concepts for Alexa Skills](https://developer.amazon.com/en-US/docs/alexa/account-linking/account-linking-concepts.html)

**Comment by shreyys** [comment]
@olegandreyev-okta  It is how OAuth works with Alexa, the API expects the auth code from Okta. And Auth code cannot be generated without user's credentials. 
Help me understand, what is this used for?
Coz, I feel this is the code we need. 

```
class OktaOidcAuthenticateTask: OktaOidcTask {
    
    func authenticateWithSessionToken(sessionToken: String,
                                      delegate: OktaNetworkRequestCustomizationDelegate? = nil,
                                      callback: @escaping (OKTAuthState?, OktaOidcError?) -> Void) {
        self.downloadOidcConfiguration() { oidConfig, error in
            guard let oidConfig = oidConfig else {
                callback(nil, error)
                return
            }
            
            let codeVerifier = OKTAuthorizationRequest.generateCodeVerifier()
            let codeChallenge = OKTAuthorizationRequest.codeChallengeS256(forVerifier: codeVerifier)
            let state = OKTAuthorizationRequest.generateState()
            var additionalParameters = self.config.additionalParams ?? [String : String]()
            additionalParameters["sessionToken"] = sessionToken
            
            let request = OKTAuthorizationRequest(
                configuration: oidConfig,
                clientId: self.config.clientId,
                clientSecret: nil,
                scope: self.config.scopes,
                redirectURL: self.config.redirectUri,
                responseType: OKTResponseTypeCode,
                state: state,
                nonce: OKTAuthorizationRequest.generateState(),
                codeVerifier: codeVerifier,
                codeChallenge: codeChallenge,
                codeChallengeMethod: OKTOAuthorizationRequestCodeChallengeMethodS256,
                additionalParameters: additionalParameters
            )
            
            OKTAuthState.getState(withAuthRequest: request, delegate: delegate, callback: { authState, error in
                callback(authState, error)
            })
        }
    }
}
```

**OKTAuthState.getState()** method has authentication code request.

```
extension OKTAuthState {

    static func getState(withAuthRequest authRequest: OKTAuthorizationRequest, delegate: OktaNetworkRequestCustomizationDelegate? = nil, callback: @escaping (OKTAuthState?, OktaOidcError?) -> Void ) {
        
        let finalize: ((OKTAuthState?, OktaOidcError?) -> Void) = { state, error in
            callback(state, error)
        }

        // Make authCode request
        OKTAuthorizationService.perform(authRequest: authRequest, delegate: delegate, callback: { authResponse, error in
            guard let authResponse = authResponse else {
                finalize(nil, OktaOidcError.APIError("Authorization Error: \(error!.localizedDescription)"))
                return
            }

            guard let _ = authResponse.authorizationCode,
                  let tokenRequest = authResponse.tokenExchangeRequest() else {
                    finalize(nil, OktaOidcError.unableToGetAuthCode)
                    return
            }

            // Make token request
            OKTAuthorizationService.perform(tokenRequest, originalAuthorizationResponse: authResponse, delegate: delegate, callback:
            { tokenResponse, error in
                guard let tokenResponse = tokenResponse else {
                    finalize(nil, OktaOidcError.APIError("Authorization Error: \(error!.localizedDescription)"))
                    return
                }

                let authState = OKTAuthState(authorizationResponse: authResponse, tokenResponse: tokenResponse)
                finalize(authState, nil)
            })
        })
    }
}
```

**Comment by oleggnidets-okta** [comment]
@shreyys 
Method `authenticateWithSessionToken`
`downloadOidcConfiguration` - downloads configuration from `.well-known/openid-configuration` file.
Sets up request, generating PKCE values (note, `codeVerifier` and `codeChallenge` **is not** Auth Code). 

Method `getState`
Sends the request with PKCE values, session token to get `Auth Code`. 
Exchanges `Auth Code` for tokens. 
`tokenResponse` contains Access, ID, Refresh tokens. The Access Token is used to communicate with server. 

> It is the only way it's working, the API expects the auth code from Okta.

Could you please provide guide/documentation you follow?

**Comment by shreyys** [comment]
> Sends the request with PKCE values, session token to get `Auth Code`.

That's all i need. I just want this auth code from the SDK.



> Could you please provide guide/documentation you follow?

The steps are defined in the URL. 
[Alexa App linking](https://developer.amazon.com/en-US/docs/alexa/account-linking/app-to-app-account-linking-starting-from-your-app.html#step-1)

To get the auth code from OKTA, I'm using below URL on webview instance.
https://${yourOktaDomain}/oauth2/default/v1/authorize?client_id=0oabucvy
c38HLL1ef0h7&response_type=code&scope=openid&redirect_uri=https%3A%2F%2Fexample.com&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601

When a user authenticates, the auth code is returned to redirectURL as query parameter
http://localhost:8080/?code=P5I7mdxxdv13_JfXrCSq&state=state-296bc9a0-a2a2-4a57-be1a-d0e2fd9bb601
which my iOS app detects and passes it to [Alexa API ](https://developer.amazon.com/en-US/docs/alexa/account-linking/app-to-app-account-linking-starting-from-your-app.html#step-6)

**Comment by oleggnidets-okta** [comment]
Hi @shreyys,
I raised your issue to the team. We strongly believe that Auth Code mustn't be shared and exposed in the SDK' public API. 
As I said above, make sure that your flow is correct, because Okta as Authorization Server authenticates the user and gives the Access Token. It's not responsibility of Alexa in your case. 

If you believe you still need Auth Token, you may fork the repo and make the changes according to your case.

**Comment by oleggnidets-okta** [comment]
I close the issue. @shreyys If you have any questions or problems, feel free to open a new issue or contact [our support team](support.okta.com/).
Thanks for using Okta 🙌
