### ISSUE TITLE
iOS 14.5 ASWebAuthenticationSession retaining user session

### ISSUE THREAD

**Issue by harkmall** [okta/okta-oidc-ios#294]
I have noticed an issue beginning in iOS 14.5 where the `ASWebAuthenticationSession` will retain a log-in session when the same implementation in 14.4 and earlier will not.

Note that we are currently **not** signing the user out of the Okta browser session due to the UX "issues" described here: https://github.com/okta/okta-oidc-ios/issues/252

Has something changed in 14.5? Is anyone else is experiencing this issue?

This is the code in question:
```    // ASWebAuthenticationSession doesn't work with guided access (rdar://40809553)
    if (!UIAccessibilityIsGuidedAccessEnabled()) {
      __weak OIDExternalUserAgentIOS *weakSelf = self;
      NSString *redirectScheme = request.redirectScheme;
      ASWebAuthenticationSession *authenticationVC =
          [[ASWebAuthenticationSession alloc] initWithURL:requestURL
                                        callbackURLScheme:redirectScheme
                                         completionHandler:^(NSURL * _Nullable callbackURL,
                                                             NSError * _Nullable error) {
        __strong OIDExternalUserAgentIOS *strongSelf = weakSelf;
        if (!strongSelf) {
            return;
        }
        strongSelf->_webAuthenticationVC = nil;
        if (callbackURL) {
          [strongSelf->_session resumeExternalUserAgentFlowWithURL:callbackURL];
        } else {
          NSError *safariError =
              [OIDErrorUtilities errorWithCode:OIDErrorCodeUserCanceledAuthorizationFlow
                               underlyingError:error
                                   description:nil];
          [strongSelf->_session failExternalUserAgentFlowWithError:safariError];
        }
      }];
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
      if (@available(iOS 13.0, *)) {
          authenticationVC.presentationContextProvider = self;
      }
#endif
      _webAuthenticationVC = authenticationVC;
      openedUserAgent = [authenticationVC start];
    }
```

In 14.5, after the user has logged in, logged out and then starts a login again, the `completionHandler` will get called right after the `start` and the webview gets shown. 

Setting `noSSO = true` does fix this issue, but wondering if there is another solution as that breaks our "remember username" functionality.

**Comment by bryanapellanes-okta** [comment]
@harkmall,
Thanks for reaching out!  I'll bring this to the attention of our iOS developers, and someone will comment here with more.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-395477

**Comment by sergeyprybysh** [comment]
I was about to open the same issue. Following this one.

**Comment by p1xel** [comment]
Adding the following line to the code block below (in OKTExternalUserAgentIOS.m) fixes the issue:

`authenticationVC.prefersEphemeralWebBrowserSession = YES;`

```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
      if (@available(iOS 13.0, *)) {
          authenticationVC.presentationContextProvider = self;
          authenticationVC.prefersEphemeralWebBrowserSession = YES;
      }
#endif
```

This line is already present in OKTExternalUserAgentNoSsoIOS.m, which is why the 'no SSO' case works.

**Comment by harkmall** [comment]
Any updates here @oleggnidets-okta ?

**Comment by oleggnidets-okta** [comment]
Hey @harkmall,
My apologies for the late reply.
I'm testing the issue and can reproduce that. From my perspective, it's expected and correct behavior of `ASWebAuthenticationSession` in iOS 14.5. Let's refer to documentation. 

> An ephemeral session improves security but prevents reusing the result of a previously successful authentication, potentially forcing the user to reenter credentials. As a result, it’s typically best to let the user choose whether to request ephemeral browsing.
[Ref.](https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service?language=objc) 

If `prefersEphemeralWebBrowserSession = false` then authorization sessions are shared and a user can log in automatically without reentering credentials. You may notice that the Access Token is re-generated every time you try to start new authorization session. 

I believe the functionality was broken in Apple framework before iOS 14.5. Now it works according to documentation. 
I suggest you using sign out despite minor UI issue on alert. The users will have possibility manage their session by their own.

**Comment by harkmall** [comment]
Thanks for looking into that @oleggnidets-okta. Looks like we'll have to enable `noSSO`.
