### ISSUE TITLE
Logged in automatically with old user after deleting and reinstalling the iOS application.

### ISSUE THREAD

**Issue by kc-bandari** [okta/okta-oidc-ios#299]
Deleted the application without logging out from okta. After reinstalling the application and trying to log in, the login page displayed for split second, and the user has logged in automatically without entering any user details.

Tried to revoke the token from the keychain.
Cleared all tokens from the keychain.
The issue is still reproducible.

If the user is logged out before deleting the application, the login process works as expected.

**Comment by oleggnidets-okta** [comment]
Hi @kc-bandari,
Thanks for the issue! 

At first glance, the issue relates to native `ASWebAuthenticationSession`. We use that component to manage sign in/sign out. Unfortunately, there's no access to manage the component, we cannot remove cache or cookies.  

Anyway, I reported internal issue to investigate it. OKTA-411478

**Comment by oleggnidets-okta** [comment]
I was looking for a way to avoid this behavior but nothing seems working. 
Authentication session is managed by `ASWebAuthenticationSession`. 

For some reason it stores a session even after deleting the app. There's no way to clear the session manually except going to `Settings` -> `Safari` -> `Clear History and Website Data`. 
As a suggestion you may use [`noSSO`](https://github.com/okta/okta-oidc-ios#disable-single-sign-on-for-the-authentication-session) parameter to make a private session.

**Comment by kc-bandari** [comment]
Thank you for the response. 

I tried using `authenticationVC.prefersEphemeralWebBrowserSession = YES;` and `noSSO`.
Which is worked as expected. But `remember me`  fails to populate `email` after `logout`.

It seems to remember me is handled by `ASWebAuthenticationSession `

**Comment by oleggnidets-okta** [comment]
Hi @kc-bandari,
You're right - functionality is handled by `ASWebAuthenticationSession`. But you can pass `login_hint` configuration parameter, as [described here](https://github.com/okta/okta-oidc-ios#configuration-object).

**Comment by kc-bandari** [comment]
@oleggnidets-okta Thank you, that helped me. Could you please provide the documented link, what additional params I can add to the configuration?

**Comment by oleggnidets-okta** [comment]
You can find [parameters here](https://developer.okta.com/docs/reference/api/oidc/#request-parameters).
You may consider to use `"prompt": "login"` instead of `noSSO` option. It always shows the login screen but respects remember me functionality. 

I hope it helps just test how it works in your case.

**Comment by kc-bandari** [comment]
@oleggnidets-okta Thank you for the solution. This helped me a lot. 
One last question, Can we disable the alert before login?

![Alert](https://user-images.githubusercontent.com/68754019/127161981-f7e1edd1-0e36-480e-9ca7-126164744ec1.png)

**Comment by oleggnidets-okta** [comment]
@kc-bandari Only one way to avoid this alert is using `noSSO = true`. 
We know that is annoying alert 😞 Unfortunately, we cannot do nothing because it's managed by Apple' `ASWebAuthenticationSession`. 

Related issue in AppAuth library [#456](https://github.com/openid/AppAuth-iOS/issues/456).

**Comment by kc-bandari** [comment]
@oleggnidets-okta Thank you... Helped me a lot.

Shall I close this issue or keep it open?

**Comment by oleggnidets-okta** [comment]
@kc-bandari You're welcome!
I close the issue. If you have any issue or question, feel free to open a new issue.

Thanks for using Okta!
