### ISSUE TITLE
okta-oidc fails to build on M1 mac.

### ISSUE THREAD

**Issue by munkledata** [okta/okta-oidc-ios#301]
I have a react native app that builds fine on our intel macs, I'm testing out an m1 mac and our app is failing to build with this error: 

debug       @objc OktaOidc.OktaOidc.init(configuration: OktaOidc.OktaOidcConfig?) throws -> OktaOidc.OktaOidc in libOktaOidc.a(OktaOidc.o)
      reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned OktaOidc.OktaOidcStateManager?, @unowned __C.NSError?) -> () to @escaping @callee_guaranteed (@guaranteed OktaOidc.OktaOidcStateManager?, @guaranteed Swift.Error?) -> () in libOktaOidc.a(OktaOidc.o)
      @objc static OktaOidc.OktaOidcConfig.default() throws -> OktaOidc.OktaOidcConfig in libOktaOidc.a(OktaOidcConfig.o)
      @objc OktaOidc.OktaOidcConfig.init(with: [Swift.String : Swift.String]) throws -> OktaOidc.OktaOidcConfig in libOktaOidc.a(OktaOidcConfig.o)
      @objc OktaOidc.OktaOidcConfig.init(fromPlist: Swift.String) throws -> OktaOidc.OktaOidcConfig in libOktaOidc.a(OktaOidcConfig.o)
      @objc OktaOidc.OktaOidcStateManager.validateToken(idToken: Swift.String?) -> Swift.Error? in libOktaOidc.a(OktaOidcStateManager.o)

debug       @objc static OktaOidc.OktaOidcStateManager.decodeJWT(Swift.String) throws -> [Swift.String : Any] in libOktaOidc.a(OktaOidcStateManager.o)
      ...

debug ld: symbol(s) not found for architecture arm64

debug clang: error: linker command failed with exit code 1 (use -v to see invocation)

okta oidc version is: 3.10.2 as OktaSdkBridgeReactNative 1.12.0 depends on that version

**Comment by oleggnidets-okta** [comment]
Hi @munkledata
Unfortunately, I have no possibility to check a build on M1. 
In overall, I guess that's not library related issue, but project (environment) setup. 

I see some workarounds proposed in React Native repo [here](https://github.com/facebook/react-native/issues/31118#issuecomment-811881922) and [here](https://github.com/react-native-community/discussions-and-proposals/issues/295). Also, I can see some suggestions in [stackoverflow](https://stackoverflow.com/questions/65364886/react-native-on-apple-silicon-m1-the-linked-library-libpods-projectname-a-is).

If you will be able to fix the issue, please let us know a workaround. We'll highly appreciate your input here!

**Comment by munkledata** [comment]
> stackoverflow

I was able to successfully build by following the suggestions in this post: https://github.com/facebook/react-native/issues/31118#issuecomment-867292214

and this post: https://github.com/facebook/react-native/issues/31118#issuecomment-811881922

my understanding would be that I am now running the simulators code in rosetta because its building x86 instead of arm64?

**Comment by oleggnidets-okta** [comment]
> my understanding would be that I am now running the simulators code in rosetta because its building x86 instead of arm64?

Yes, I believe you're right. We should migrate to xcframework to make it possible to support Apple Silicon arch. I created internal task for our team, OKTA-414819. 

I close this issue for now as it seems fixed.

Many thanks for your input and feedback!

**Comment by bdrelling** [comment]
@oleggnidets-okta can you consider re-opening this issue? I wanted to make a new issue but saw this already existed. 

> Could not find module 'OktaOidc' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/brian/Library/Developer/Xcode/DerivedData/Medly-gpikfwzqfbebbcflgpzlxzsalgfw/Build/Products/Debug-Beta-iphonesimulator/OktaOidc.swiftmodule

Can you please give me some visibility into the status of `OKTA-414819`? This feels like a critical priority IMO, so many teams (including my own) are switching entirely to M1s and this will result in a massive, massive blocker to our productivity overall.

I'm happy to assist, please let me know how I can do so.

**Comment by bdrelling** [comment]
@oleggnidets-okta can you consider re-opening this issue? I wanted to make a new issue but saw this one already existed. I believe my error is related:

> Could not find module 'OktaOidc' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/brian/Library/Developer/Xcode/DerivedData/Medly-gpikfwzqfbebbcflgpzlxzsalgfw/Build/Products/Debug-Beta-iphonesimulator/OktaOidc.swiftmodule

Can you please give me some visibility into the status of `OKTA-414819`? This feels like a critical priority IMO, so many teams (including my own) are switching entirely to M1s and this will result in a massive, massive blocker to our productivity overall.

I'm happy to assist, including any testing I can do on an M1 for your sake, but I think the issue would absolutely be tied to the lack of an XCFramework if that's still the case. 

Please let me know how I can help!

**Comment by oleggnidets-okta** [comment]
Hi @bdrelling,

Sorry to hear you meet the issue on M1. 

The issue was fixed based on [comment above](https://github.com/okta/okta-oidc-ios/issues/301#issuecomment-885261950). Unfortunately, I don't have possibility to check on M1, neither my colleague @mikenachbaur-okta.

So we appropriate any input here.

**Comment by bdrelling** [comment]
@oleggnidets-okta Great news! I spoke too soon. These libraries are a-ok on an M1. 

Feel free to reach out if you'd like help testing anything else on M1. Given that your libraries support our app, I'm happy to help support your libraries however I can. 👍 

Thanks for re-opening this issue in the meantime! I think it can be closed. Anyone else finding this will see my findings.

**Comment by oleggnidets-okta** [comment]
@bdrelling Thanks for your contribution! Feel free to reach us out.
