### ISSUE TITLE
Persistent SSO in WKWebView or SFSafariViewController

### ISSUE THREAD

**Issue by peter-chan-hkmci** [okta/okta-oidc-ios#302]
Dear all,

I have integrated the sdk and enabled persistent sso in okta.
Safari and the native app are able to share the same authentication session.

However, the authentication session cannot be detected when the app open an embedded web view to access the other webapp registered in okta. 

I have tried WKWebView and SFSafariViewController, no luck due to the isolated cookies between apps and safari.

Did I trying it wrong? or any workaround solution?

**Comment by oleggnidets-okta** [comment]
Hello @peter-chan-hkmci!

Thanks for using Okta and asking for help!
Could you, please, explain in more details the following statement? What do you mean by the native app? 

> Safari and the native app are able to share the same authentication session

Have you tried `ASWebAuthenticationSession`? It's recommended to authenticate the users through this component.

**Comment by peter-chan-hkmci** [comment]
Thanks for replying!

After I login to Okta by using this okta-oidc sdk with ```signInWithBrowser``` function, I can access to ```https://{okta-domain}/app/UserHome``` in Safari without login.

However, for example, I would like to access another okta app (web app), like ```https://{okta-domain}/app/UserHome```, in the ios app by using the embedded web view (like WKWebView or SFSafariViewController).

I don't know if I am wrong, ```ASWebAuthenticationSession``` is used for authenticating user but not accessing to a webapp.

**Comment by oleggnidets-okta** [comment]
Thanks for super helpful info provided! 

I recorded internal task to investigate your case, ref. OKTA-413876.

**Comment by peter-chan-hkmci** [comment]
Thanks!

Is it possible that save the session cookies after login successfully by using ```ASWebAuthenticationSession```, then have a new function that get the session cookies for ```WKWebView``` and ```SFSafariViewController```?

**Comment by oleggnidets-okta** [comment]
So far what I can see there's no way to share cookies, authorization sessions or anything else between these two browsers. 
Apple doesn't bring any API to make it possible. I think it's because of security reasons.
