### ISSUE TITLE
UIAlertController Sign-out messaging says Sign-In

### ISSUE THREAD

**Issue by levieggertcru** [okta/okta-oidc-ios#324]
In OktaOidc Version 3.10.8 I'm calling the signOutOfOkta method with arguments OktaOidcStateManager and UIViewController which then presents an UIAlertController asking the user to confirm sign out.  This UIAlertController is being configured and presented from within the OktaOidc SDK.  The issue I am seeing is the alert title is stating Okta wants to Sign In when in reality the user is Signing Out. 

Any status on fixing this bug?

Is there a way clients can configure UIAlertController messaging in your SDK?

**To Reproduce**
Call signOutOfOkta with the OktaOidcStateManager and UIViewController and presented alert will say Sign In.

**Expected behavior**
UIAlertController should say Sign Out.

**Screenshots**

![okta-sign-out](https://user-images.githubusercontent.com/59846460/144628265-573b5b79-b5b1-4738-8a77-2e53459598a6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11, 
 - OS: iOS 15

**Comment by oleggnidets-okta** [comment]
Hi @levieggertcru 

Thanks for your input. 

The alert is presented by Apple and there's no way to configure text shown 😞 The solution may be only setting `noSSO` as `true`. But keep in mind it will disable shared sessions. 
We keep an eye on possibility to fix the UX.

Here we have [description of the issue](https://github.com/okta/okta-oidc-ios#ios-shows-permission-dialogapp-wants-to-use-auth-domain-to-sign-in-for-okta-sign-out-flows). Also [related another issue](https://github.com/okta/okta-oidc-ios/issues/252).

**Comment by levieggertcru** [comment]
Hey @oleggnidets-okta thank you for the quick response and additional information regarding this issue.  I did notice that ASWebAuthenticationSession is available in iOS 12 and up.  I'm curious what is being used for iOS 11 to sign out and terminate the session?  Is that noted in your documentation?  

Thank you.

<img width="1012" alt="ASWebAuthenticationSession-iOS12+" src="https://user-images.githubusercontent.com/59846460/144637936-b5616288-05ff-4a5f-be95-dc1aa615ee60.png">

**Comment by mikenachbaur-okta** [comment]
When the SDK is used on a device running an OS earlier than 12.0, it switches to use either SFAuthenticationSession on iOS 11, or SFSafariViewController on iOS 9-10

**Comment by levieggertcru** [comment]
Thanks @mikenachbaur-okta.
