### ISSUE TITLE
Modify readFromSecureStorage() and writeToSecureStorage() calls to throw errors

### ISSUE THREAD

**Issue by emanor-okta** [okta/okta-oidc-ios#331]
Currently if `OktaOidcStateManager.swift` encounters an error during `readFromSecureStorage()` or `writeToSecureStorage()` calls, that error is not thrown.

In the case of `readFromSecureStorage()` which returns an optional, nil is returned if there is an error. For key_not_found returning nil is fine, but if an encoding error, or no data is found for a key, it would be beneficial for the application to be able to handle this situation.

In the case of `writeToSecureStorage()`, there is no return type. If an error occurs it is logged instead. Would suggest to throw the error to the calling application and not log it, rather let the calling application decide how to handle it.

**Comment by oleggnidets-okta** [comment]
Hey @emanor-okta 
Totally agree, error handling should be improved here. 
Internal ref. OKTA-460840

**Comment by mikenachbaur-okta** [comment]
I wanted to revisit this issue to say that these sorts of problems have been addressed in the new [okta-mobile-swift SDK](https://github.com/okta/okta-mobile-swift). Reading and writing to storage all produces expressive errors, to know when and what is going wrong. If you have further questions, or if there are cases in that SDK where you feel that errors should be better reported, please let us know.
