### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by thukaram915213** [okta/okta-oidc-ios#340]
### Describe the bug?

Login with X credentials and logout. Trying to login with Y credentials, unable to login into okta. 

This is the error response as the result of calling the authenticate method.
APIError : "Authorization Error: Unexpected response format while retrieving authorization code. Status code:200"

Here’s how I get the session token:

OktaAuthSdk.authenticate(with:{okta domain}, username: {user name}, password: {password}, onStatusChange: { (status) in
}) {(error) in
}

Access token is obtained like below and the failure happens here:

oidcClient.authenticate(withSessionToken: sessionToken, callback: {stateManager, error in
})

On logout 
dClient.signOut(with: [.revokeAccessToken, .removeTokensFromStorage, .revokeRefreshToken, .revokeTokensOptions], authStateManager: stateManager, from: UIViewController()) { currentOption in

    } completionHandler: { success, failedOptions in

  }
<img width="313" alt="Screenshot 2022-05-10 at 6 17 55 PM" src="https://user-images.githubusercontent.com/40417911/167634890-201b9b40-0940-4c71-a05a-714e954f4fcd.png">

### What is expected to happen?

It should login smoothly.

### What is the actual behavior?

Getting Authorization Error: Unexpected response format

### Reproduction Steps?

Login with X user and logout. Then try to login with Y user.

### SDK Version(s)

3.11.1

**Comment by mikenachbaur-okta** [comment]
Thank you for reporting this @thukaram915213, I tried this in the [custom sign in sample app](https://github.com/okta/samples-ios/tree/master/custom-sign-in), and using your logout call (with the list of options you specified) I was unable to reproduce your problem. 

Is there a possibility you can set a breakpoint to determine where and when this error is being generated, and perhaps to see what the raw response was from the server?
