### ISSUE TITLE
 OktaOidcKeychain.clearAll() clears entire keychain instead of just okta related keys

### ISSUE THREAD

**Issue by derekpitts28** [okta/okta-oidc-ios#342]
### Describe the bug?

Describe the bug
When OktaOidcKeychain.clearAll() is called, it also deletes any items the app may have stored in the keychain.

### What is expected to happen?

Expected behavior
OktaOidcKeychain.clearAll() should only clear Oidc related items from the keychain.

### What is the actual behavior?

Expected behavior
OktaOidcKeychain.clearAll() clears all keychain for app.

### Reproduction Steps?

Save an item in the keychain in the default access group
Call OktaOidcKeychain.clearAll()
Get errSecItemNotFound when trying to retrieve your keychain item

### Additional Information?
This was incredibly hard to track down and very frustrating that an sdk would delete the entire keychain affecting other processes. Would be wonderful if this could get hotfixed 🙏 

### SDK Version(s)

3.10.2

### Build Information

iPhone 13 ios 15.2.1

**Comment by aarongranick-okta** [comment]
@derekpitts28 Thank you for bringing this to our attention! I will pass this along to our mobile engineers for further investigation.

**Comment by mikenachbaur-okta** [comment]
Thank you @derekpitts28, this API is working as expected.  The `OktaOidcKeychain` is a simple wrapper around the iOS keychain, and doesn't restrict itself to Okta-related items.

I suggest you try the `OktaOidcStateManager.removeFromSecureStorage()` method to remove the Okta-related keychain item.
