### ISSUE TITLE
@available not allowed for stored properties in Xcode 14

### ISSUE THREAD

**Issue by rakibul-islam-yankees** [okta/okta-oidc-ios#344]
### Describe the bug?

In Xcode 14, a stored property cannot be marked with an @available tag. This causes the okda-oidc-ios library to fail at compile time. In OktaOidcConfig.swift, the property noSSO is marked with `@available(iOS 13.0, *)`

### What is expected to happen?

Library should compile successfully.

### What is the actual behavior?

Library throws a compile-time error.

### Reproduction Steps?

1. Add latest Okta-oidc-ios library to project via Swift Package Manager.
2. Attempt to compile project

### SDK Version(s)

3.11.1

### Build Information

Xcode 14.0 beta, target device iPhone 13 Pro (Simulator), library imported into project using Swift Package Manager

**Comment by mikenachbaur-okta** [comment]
@rakibul-islam-yankees OktaOidc 3.11.2 has just been released with a fix to this issue. Please let us know if there's anything else you discover in trying Xcode 14.

**Comment by imougy** [comment]
Thanks for the fix but pod update picks up version 3.11.1 and not the latest.  Is this intentional?

**Comment by imougy** [comment]
I looked at the pod spec and it is 3.11.2?  Maybe something on my side, will dig in!
