### ISSUE TITLE
OktaOidc alongside GoogleSSO library 

### ISSUE THREAD

**Issue by AlexSlukin** [okta/okta-oidc-ios#351]
### Describe the bug?

I have found an issue when I use the Google SSO library [](https://github.com/google/GoogleSignIn-iOS) together with the OktaOidc library in my SPM module. When I build the module **for macOS platform** I get an error "9 duplicate symbols for architecture arm64", so there is a conflict in naming in the OIDLoopbackHTTPServer.h and m files because Google SSO uses AppAuth library as a dependency and OktaOidc has it hardcoded in the code.

### What is expected to happen?

There is no conflict between Google SSO and OktaOidc library. SPM package with those 2 dependencies could run on the macOS platform.

### What is the actual behavior?

```
duplicate symbol '_OBJC_CLASS_$_HTTPConnection' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_CLASS_$_HTTPServer' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_CLASS_$_HTTPServerRequest' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_CLASS_$_TCPServer' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_METACLASS_$_HTTPConnection' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_METACLASS_$_HTTPServer' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_METACLASS_$_HTTPServerRequest' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_OBJC_METACLASS_$_TCPServer' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
duplicate symbol '_TCPServerErrorDomain' in:
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/OktaOidc_AppAuth.o
    /Users/aleksandr/Library/Developer/Xcode/DerivedData/apple-authentication-aidyopsrxurqqkbevlkypefffsjd/Build/Products/Debug/AppAuth.o
ld: 9 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduction Steps?

Create a swift package manager project with these two dependencies, create one target with some files and the test target with this new target dependency, so when you build it for the macOS platform you will get the error "9 duplicate symbols for architecture arm64". 
For example, something like this:
<img width="759" alt="Screenshot 2023-03-08 at 16 31 02" src="https://user-images.githubusercontent.com/87066102/223756172-e3bc5b11-e42b-4b15-972f-81fa45288f2f.png">

2nd method: add these 2 libraries to the macOS application and try to build it.

### SDK Version(s)

Google SSO 7.0.0 SPM version
OktaOidc 3.11.2 SPM version

**Comment by mikenachbaur-okta** [comment]
Hi @AlexSlukin, we're actually replacing okta-oidc-ios with a new SDK that fixes a number of issues, including the one you mention here.  Please take a look at https://github.com/okta/okta-mobile-swift for more information. Since that new library isn't based on Google's AppAuth library, there shouldn't be any symbol conflicts.

If you'd like additional background on why we made this decision, please take a look at [an article I wrote for the Okta Developer Blog](https://developer.okta.com/blog/2022/08/30/introducing-the-new-okta-mobile-sdks), which goes into this in more detail.

Please don't hesitate to ask additional questions if you have any.
