### ISSUE TITLE
Consistent placeholders and labels

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#72]
Sweep through readme and code to make sure labels and placeholders follow the pattern here: https://oktawiki.atlassian.net/wiki/spaces/UX/pages/470681125/Developer+Experience+-+Okta+Domain+Labels

- [ ] `https://{yourOktaDomain}` (not `https://{yourOktaDomain}.com`)
- [ ] `{clientId}`
- [ ] `{clientSecret}`
- [ ] `{scheme}`

**Comment by wdawson** [comment]
@nbarbettini do we have a public version of that doc anywhere in something like a CONTRIBUTING.md?

**Comment by nbarbettini** [comment]
Not yet, but long term we plan on publishing it.
