### ISSUE TITLE
Split up library and demo, replace with test harness

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#76]
Currently, this repo contains both the SDK and a demo app. This gets a little confusing because it's hard to tell how they are separated. We are publishing https://github.com/okta/samples-ios soon, which will be a clear home for all samples going forward.

We should:
- [ ] Determine what a good test harness looks like in this repo
- [ ] Remove everything else sample-related

Please collaborate with @IldarAbdullin-okta  to determine the best way to do this.

**Comment by IldarAbdullin-okta** [comment]
So, the structure is following:
- OIDC repo contains small sample app that also behaves as a test-harness with the unit and integration tests on board
- OIDC sample app repo contains application with the end-to-end tests on board
