### ISSUE TITLE
Swift client for Authentication API

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#81]
We need to build an SDK for Swift that communicates with our Authentication API (https://developer.okta.com/docs/api/resources/authn). This will be in a new repo (https://github.com/okta/okta-auth-swift). 

Here is an example of an existing authentication SDK: https://github.com/okta/okta-auth-java

The product and technical requirements for these SDKs is here:
https://oktawiki.atlassian.net/wiki/spaces/PM/pages/584942575/Authentication+SDK+product+spec
https://oktawiki.atlassian.net/wiki/spaces/eng/pages/463831327/Technical+Design+for+AuthN+SDKs

The requirements for the MVP are in https://github.com/okta/okta-auth-swift/issues

**Comment by IldarAbdullin-okta** [comment]
Outdated, closing.
