### ISSUE TITLE
Native sign-in method

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#82]
The SDK should provide a method to easily do the flow described in #78.

First, a Swift client for the [Authentication API]() needs to be created. This work will be done in [okta-auth-swift](https://github.com/okta/okta-auth-swift) (see #81).

Then, this library must expose a method to start a sign-in request and pass the username/password directly. We will deprecate the existing `login(username: string, password: string)` method. This method will kick off the flow described in #78. This will result in one of two things:
1. Login was valid and resulted in tokens. Like the existing `login` method, this should automatically store the tokens. Allow the developer to segue to a new view.
2. The transaction response did not contain status `SUCCESS`, or some other error occurred (e.g., network error). Allow the developer to access the error object, or handle the status.

The result is that a developer can build their own native sign-in UI, use this new method to perform the sign-in flow (with no browser popup), and store tokens on the device.

**Comment by codal-ashahu** [comment]
Is this feature still being implemented or taken off the roadmap after this? 
#### [ Remove Resource Owner Password flow support #84](/okta/okta-sdk-appauth-ios/issues/84)

We are building an App that currently uses 1.0.1 release that has singin with username and password but refresh token feature is not working on that release putting us in tight spot.

Should we wait for this feature to be implemented or go with browser based authentication with popup?

**Comment by nbarbettini** [comment]
@codal-ashahu This feature replaces #84. We weren't able to replace the Resource Owner Password flow immediately in 2.0 since we had to build a supporting library. The 2.1.0 release will include this new functionality to do native (non-browser) sign-in but without the security risk of the Resource Owner Password flow.

I'm not sure why refreshing a token isn't working for you - that should work even in 1.0.1. Sorry about that! Have you opened an issue for it?

**Comment by nbarbettini** [comment]
@IldarAbdullin-okta @olexiylebedyev-okta  Did we end up deciding to model this native sign-in method like the Android one? i.e. as `authenticate(sessionToken)`? I seem to remember that, but it's buried in PRs 😉 I think my description in this issue is not accurate anymore, just wanted to confirm.

**Comment by chielos24** [comment]
hi Nate @nbarbettini. We have the requirement to do native (non-browser) sign-in flow for our newly build app. Stakeholder want a seamless experience on launch of the app, it would help us greatly.

- Is this a PKCE flow?
- Does it support SSO with an webapplication?

Can we perhaps:
- help on developing this in IOS.
- share a Beta version on this?

**Comment by codal-ashahu** [comment]
this is a possible linked issue https://github.com/okta/okta-sdk-appauth-ios/issues/140

**Comment by nbarbettini** [comment]
@chielos24 Yes, we built this functionality so it's possible to create a seamless (native) sign-in experience without leaving the app.

* Is this a PKCE flow? Under the hood, yes. It uses the OpenID Connect authorization code flow just like the browser sign-in flow.

* Does it support SSO with an webapplication? **No.** There is a tradeoff here: signing in with a browser makes the web session available for SSO in the browser, while signing in with custom native UI does not. If you need SSO in the browser, you'll need to stick with browser sign-in.

Building it requires this library and the [okta-auth-swift](https://github.com/okta/okta-auth-swift) library. Please see our [custom sign-in UI sample](https://github.com/okta/samples-ios/tree/master/custom-sign-in) for a working demo.
