### ISSUE TITLE
Build demo of native sign-in with AppAuth SDK and Swift AuthN SDK

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#83]
After #82 and #81 are done, we need to build a sample app (like #78) that performs native sign-in using the new functionality we added to our libraries.

**Comment by nbarbettini** [comment]
The sample app must contain this functionality:
* Present a view that collects the user's email and password and starts primary authentication.
* If the response from the Authentication API is an error (such as invalid credentials), display the error.
* If the response from the Authentication API is `SUCCESS`, the AppAuth SDK should store the tokens normally.
* If the response from the Authentication API is not an error, but is not `SUCCESS` (such as `MFA_REQUIRED`), display a view with: "Something unexpected happened. Status: {status}"

**Comment by IldarAbdullin-okta** [comment]
Outdated, closing
