### ISSUE TITLE
Sign out method

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-ios#89]
With #87, we are adding the ability to sign out of Okta (end the Okta session). We also need to add and document a method for signing out of the app (destroying the user's tokens). This method should:

1. Throw away tokens stored in the Keychain (i.e. `clearAuthState()`)
2. Revoke access and refresh tokens

We should give developers the ability to skip (2) if they do not want to incur a network request. However, the default should be true (revoke).

Note that the user _may_ have an access token and _may_ have a refresh token, but they will not always have one or both. This method must check to see whether either of those token types are stored, and revoke them if they exist and if the developer did not pass a parameter to disable revocation.

**Comment by IldarAbdullin-okta** [comment]
Fixed in https://github.com/okta/okta-oidc-ios/pull/182
